//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenter.Client.Mvc.Resources.EMS {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceCenter.Client.Mvc.Resources.EMS.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 登记 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEvent_AddTitle {
            get {
                return ResourceManager.GetString("EquipmentStateEvent_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备状态事件登记 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEvent_ManagePageTitle {
            get {
                return ResourceManager.GetString("EquipmentStateEvent_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备状态事件（{0}）登记成功。 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEvent_Save_Success {
            get {
                return ResourceManager.GetString("EquipmentStateEvent_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件名称 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEventQueryViewModel_ChangeStateName {
            get {
                return ResourceManager.GetString("EquipmentStateEventQueryViewModel_ChangeStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登记时间（止） 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEventQueryViewModel_EndCreateTime {
            get {
                return ResourceManager.GetString("EquipmentStateEventQueryViewModel_EndCreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备编码 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEventQueryViewModel_EquipmentCode {
            get {
                return ResourceManager.GetString("EquipmentStateEventQueryViewModel_EquipmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始状态 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEventQueryViewModel_FromStateName {
            get {
                return ResourceManager.GetString("EquipmentStateEventQueryViewModel_FromStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备原因组名称 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEventQueryViewModel_ReasonCodeCategoryName {
            get {
                return ResourceManager.GetString("EquipmentStateEventQueryViewModel_ReasonCodeCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备原因代码名称 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEventQueryViewModel_ReasonCodeName {
            get {
                return ResourceManager.GetString("EquipmentStateEventQueryViewModel_ReasonCodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 责任人 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEventQueryViewModel_ResponsiblePerson {
            get {
                return ResourceManager.GetString("EquipmentStateEventQueryViewModel_ResponsiblePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登记时间（起） 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEventQueryViewModel_StartCreateTime {
            get {
                return ResourceManager.GetString("EquipmentStateEventQueryViewModel_StartCreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标状态 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEventQueryViewModel_ToStateName {
            get {
                return ResourceManager.GetString("EquipmentStateEventQueryViewModel_ToStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件名称 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEventViewModel_ChangeStateName {
            get {
                return ResourceManager.GetString("EquipmentStateEventViewModel_ChangeStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备编码 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEventViewModel_EquipmentCode {
            get {
                return ResourceManager.GetString("EquipmentStateEventViewModel_EquipmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备名称 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEventViewModel_EquipmentName {
            get {
                return ResourceManager.GetString("EquipmentStateEventViewModel_EquipmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始状态 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEventViewModel_FromStateName {
            get {
                return ResourceManager.GetString("EquipmentStateEventViewModel_FromStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产线 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEventViewModel_ProductionLine {
            get {
                return ResourceManager.GetString("EquipmentStateEventViewModel_ProductionLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原因类别 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEventViewModel_ReasonCodeCategoryName {
            get {
                return ResourceManager.GetString("EquipmentStateEventViewModel_ReasonCodeCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原因代码 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEventViewModel_ReasonCodeName {
            get {
                return ResourceManager.GetString("EquipmentStateEventViewModel_ReasonCodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 责任人 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEventViewModel_ResponsiblePerson {
            get {
                return ResourceManager.GetString("EquipmentStateEventViewModel_ResponsiblePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEventViewModel_RouteOperationName {
            get {
                return ResourceManager.GetString("EquipmentStateEventViewModel_RouteOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标状态 的本地化字符串。
        /// </summary>
        public static string EquipmentStateEventViewModel_ToStateName {
            get {
                return ResourceManager.GetString("EquipmentStateEventViewModel_ToStateName", resourceCulture);
            }
        }
    }
}
