//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenter.Client.Mvc.Resources.ERP {
    using System;    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceCenter.Client.Mvc.Resources.ERP.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实际功率 的本地化字符串。
        /// </summary>
        public static string WOReportDetailViewModels_SumCOEF_PMAX
        {
            get
            {
                return ResourceManager.GetString("WOReportDetailViewModels_SumCOEF_PMAX", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 物料名称 的本地化字符串。
        /// </summary>
        public static string WOReportDetailViewModels_MaterialName
        {
            get
            {
                return ResourceManager.GetString("WOReportDetailViewModels_MaterialName", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 申报 的本地化字符串。
        /// </summary>
        public static string AntiState
        {
            get
            {
                return ResourceManager.GetString("AntiState", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 ERP领料单生成成功！ 的本地化字符串。
        /// </summary>
        public static string ERPMaterialReceipt_Add_Success {
            get {
                return ResourceManager.GetString("ERPMaterialReceipt_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认要生成领料{0}？ 的本地化字符串。
        /// </summary>
        public static string ERPMaterialReceipt_ConfirmSave {
            get {
                return ResourceManager.GetString("ERPMaterialReceipt_ConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领料生成 的本地化字符串。
        /// </summary>
        public static string ERPMaterialReceipt_Create {
            get {
                return ResourceManager.GetString("ERPMaterialReceipt_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERP领料单【{0}】不存在! 的本地化字符串。
        /// </summary>
        public static string ERPMaterialReceipt_Error_Query {
            get {
                return ResourceManager.GetString("ERPMaterialReceipt_Error_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERP领料管理 的本地化字符串。
        /// </summary>
        public static string ERPMaterialReceiptQuery_ManagePageTitle {
            get {
                return ResourceManager.GetString("ERPMaterialReceiptQuery_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库单管理 的本地化字符串。
        /// </summary>
        public static string ERPWIReport_ManagePageTitle {
            get {
                return ResourceManager.GetString("ERPWIReport_ManagePageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 入库单管理 的本地化字符串。
        /// </summary>
        public static string ERPWIReportForScrap_ManagePageTitle
        {
            get
            {
                return ResourceManager.GetString("ERPWIReportForScrap_ManagePageTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 新增报工单 的本地化字符串。
        /// </summary>
        public static string ERPWOReport_AddTitle {
            get {
                return ResourceManager.GetString("ERPWOReport_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除报工单{0} 的本地化字符串。
        /// </summary>
        public static string ERPWOReport_ConfirmDelete {
            get {
                return ResourceManager.GetString("ERPWOReport_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改报工单 的本地化字符串。
        /// </summary>
        public static string ERPWOReport_EditTitle {
            get {
                return ResourceManager.GetString("ERPWOReport_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报工单管理 的本地化字符串。
        /// </summary>
        public static string ERPWOReport_ManagePageTitle {
            get {
                return ResourceManager.GetString("ERPWOReport_ManagePageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 报工单管理 的本地化字符串。
        /// </summary>
        public static string ERPWOReportForScrap_ManagePageTitle
        {
            get
            {
                return ResourceManager.GetString("ERPWOReportForScrap_ManagePageTitle", resourceCulture);
            }
        }


        /// <summary>
        ///   查找类似 新增报工单明细 的本地化字符串。
        /// </summary>
        public static string ERPWOReportDetail_AddTitle {
            get {
                return ResourceManager.GetString("ERPWOReportDetail_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除报工单明细【箱号：{0}】 的本地化字符串。
        /// </summary>
        public static string ERPWOReportDetail_ConfirmDelete {
            get {
                return ResourceManager.GetString("ERPWOReportDetail_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【箱号:{0}】的颜色与明细其他不一样，无法添加明细！ 的本地化字符串。
        /// </summary>
        public static string ERPWOReportDetail_Error_Color {
            get {
                return ResourceManager.GetString("ERPWOReportDetail_Error_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【箱号:{0}】的分档与明细其他不一样，无法添加明细！ 的本地化字符串。
        /// </summary>
        public static string ERPWOReportDetail_Error_EffiCode {
            get {
                return ResourceManager.GetString("ERPWOReportDetail_Error_EffiCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【箱号:{0}】的转换率与明细其他不一样，无法添加明细！ 的本地化字符串。
        /// </summary>
        public static string ERPWOReportDetail_Error_EffiName {
            get {
                return ResourceManager.GetString("ERPWOReportDetail_Error_EffiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【箱号:{0}】的等级与明细其他不一样，无法添加明细！ 的本地化字符串。
        /// </summary>
        public static string ERPWOReportDetail_Error_Grade {
            get {
                return ResourceManager.GetString("ERPWOReportDetail_Error_Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【箱号:{0}】的物料号与明细其他不一样，无法添加! 的本地化字符串。
        /// </summary>
        public static string ERPWOReportDetail_Error_MaterialCode {
            get {
                return ResourceManager.GetString("ERPWOReportDetail_Error_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 箱号【{0}】不存在！ 的本地化字符串。
        /// </summary>
        public static string ERPWOReportDetail_Error_Object {
            get {
                return ResourceManager.GetString("ERPWOReportDetail_Error_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【箱号:{0}】的工单号与报工单不一样，无法添加明细！ 的本地化字符串。
        /// </summary>
        public static string ERPWOReportDetail_Error_OrderNumer {
            get {
                return ResourceManager.GetString("ERPWOReportDetail_Error_OrderNumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报工单已经申报，无法添加明细 的本地化字符串。
        /// </summary>
        public static string ERPWOReportDetail_Error_WACode {
            get {
                return ResourceManager.GetString("ERPWOReportDetail_Error_WACode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报工单明细管理 的本地化字符串。
        /// </summary>
        public static string ERPWOReportDetail_ManagePageTitle {
            get {
                return ResourceManager.GetString("ERPWOReportDetail_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERP工单生成成功！ 的本地化字符串。
        /// </summary>
        public static string ERPWorkOrder_Add_Success {
            get {
                return ResourceManager.GetString("ERPWorkOrder_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增报工单 的本地化字符串。
        /// </summary>
        public static string ERPWorkOrder_AddTitle {
            get {
                return ResourceManager.GetString("ERPWorkOrder_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认要生成工单{0}？ 的本地化字符串。
        /// </summary>
        public static string ERPWorkOrder_ConfirmSave {
            get {
                return ResourceManager.GetString("ERPWorkOrder_ConfirmSave", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 确认要生成工单BOM{0}？ 的本地化字符串。
        /// </summary>
        public static string ERPWorkBOMOrder_ConfirmSave
        {
            get
            {
                return ResourceManager.GetString("ERPWorkBOMOrder_ConfirmSave", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 工单生成 的本地化字符串。
        /// </summary>
        public static string ERPWorkOrder_Create {
            get {
                return ResourceManager.GetString("ERPWorkOrder_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERP领料单【{0}】的ERP工单【{1}】不存在! 的本地化字符串。
        /// </summary>
        public static string ERPWorkOrder_Error_Query {
            get {
                return ResourceManager.GetString("ERPWorkOrder_Error_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERP工单管理 的本地化字符串。
        /// </summary>
        public static string ERPWorkOrder_ManagePageTitle {
            get {
                return ResourceManager.GetString("ERPWorkOrder_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料名称 的本地化字符串。
        /// </summary>
        public static string ERPWorkOrder_MaterialName {
            get {
                return ResourceManager.GetString("ERPWorkOrder_MaterialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERP工单【{0}】不存在！ 的本地化字符串。
        /// </summary>
        public static string ERPWorkOrderQuery_Error_Query {
            get {
                return ResourceManager.GetString("ERPWorkOrderQuery_Error_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERP工单查询 的本地化字符串。
        /// </summary>
        public static string ERPWorkOrderQuery_ManagePageTitle {
            get {
                return ResourceManager.GetString("ERPWorkOrderQuery_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库单【{0}】需要先报工，才能入库申报！ 的本地化字符串。
        /// </summary>
        public static string WIReport_Error_Approve {
            get {
                return ResourceManager.GetString("WIReport_Error_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报工单【{0}】申报失败！ 的本地化字符串。
        /// </summary>
        public static string WOReport_StockInApply_Error {
            get {
                return ResourceManager.GetString("WOReport_StockInApply_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【{0}】已经申报成功,无法重复申报！ 的本地化字符串。
        /// </summary>
        public static string WOReport_StockInApply_Error_Again {
            get {
                return ResourceManager.GetString("WOReport_StockInApply_Error_Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报工单【{0}】申报成功！ 的本地化字符串。
        /// </summary>
        public static string WOReport_StockInApply_Success {
            get {
                return ResourceManager.GetString("WOReport_StockInApply_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报工单{0}删除成功! 的本地化字符串。
        /// </summary>
        public static string WOReport_Delete_Success {
            get {
                return ResourceManager.GetString("WOReport_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报工单{0}修改成功! 的本地化字符串。
        /// </summary>
        public static string WOReport_Edit_Success {
            get {
                return ResourceManager.GetString("WOReport_Edit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报工单【{0}】已有明细项，无法修改！ 的本地化字符串。
        /// </summary>
        public static string WOReport_Error_Edit {
            get {
                return ResourceManager.GetString("WOReport_Error_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报工单{0}新增成功! 的本地化字符串。
        /// </summary>
        public static string WOReport_Save_Success {
            get {
                return ResourceManager.GetString("WOReport_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报工单明细【箱号：{0}】新增成功 的本地化字符串。
        /// </summary>
        public static string WOReportDetail_Add_Success {
            get {
                return ResourceManager.GetString("WOReportDetail_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报工单明细【箱号：{0}】删除成功 的本地化字符串。
        /// </summary>
        public static string WOReportDetail_Delete_Success {
            get {
                return ResourceManager.GetString("WOReportDetail_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报工单号 的本地化字符串。
        /// </summary>
        public static string WOReportDetailViewModels_BillCode {
            get {
                return ResourceManager.GetString("WOReportDetailViewModels_BillCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色 的本地化字符串。
        /// </summary>
        public static string WOReportDetailViewModels_Color {
            get {
                return ResourceManager.GetString("WOReportDetailViewModels_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分档编号 的本地化字符串。
        /// </summary>
        public static string WOReportDetailViewModels_EffiCode {
            get {
                return ResourceManager.GetString("WOReportDetailViewModels_EffiCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换率 的本地化字符串。
        /// </summary>
        public static string WOReportDetailViewModels_EffiName {
            get {
                return ResourceManager.GetString("WOReportDetailViewModels_EffiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等级 的本地化字符串。
        /// </summary>
        public static string WOReportDetailViewModels_Grade {
            get {
                return ResourceManager.GetString("WOReportDetailViewModels_Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行号 的本地化字符串。
        /// </summary>
        public static string WOReportDetailViewModels_ItemNo {
            get {
                return ResourceManager.GetString("WOReportDetailViewModels_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料号 的本地化字符串。
        /// </summary>
        public static string WOReportDetailViewModels_MaterialCode {
            get {
                return ResourceManager.GetString("WOReportDetailViewModels_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 箱号 的本地化字符串。
        /// </summary>
        public static string WOReportDetailViewModels_ObjectNumber {
            get {
                return ResourceManager.GetString("WOReportDetailViewModels_ObjectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string WOReportDetailViewModels_Qty {
            get {
                return ResourceManager.GetString("WOReportDetailViewModels_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报工单编号 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_BillCode {
            get {
                return ResourceManager.GetString("WOReportViewModels_BillCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报产日期 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_BillDate {
            get {
                return ResourceManager.GetString("WOReportViewModels_BillDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制单日期 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_BillMakedDate {
            get {
                return ResourceManager.GetString("WOReportViewModels_BillMakedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制单人 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_BillMaker {
            get {
                return ResourceManager.GetString("WOReportViewModels_BillMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单据状态 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_BillState {
            get {
                return ResourceManager.GetString("WOReportViewModels_BillState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报工单类型 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_BillType {
            get {
                return ResourceManager.GetString("WOReportViewModels_BillType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报告类型 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_BillTypeId {
            get {
                return ResourceManager.GetString("WOReportViewModels_BillTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_Color {
            get {
                return ResourceManager.GetString("WOReportViewModels_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分档编号 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_EffiCode {
            get {
                return ResourceManager.GetString("WOReportViewModels_EffiCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换率 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_EffiName {
            get {
                return ResourceManager.GetString("WOReportViewModels_EffiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等级 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_Grade {
            get {
                return ResourceManager.GetString("WOReportViewModels_Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回填的ERP入库编号 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_INCode {
            get {
                return ResourceManager.GetString("WOReportViewModels_INCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料号 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_MaterialCode {
            get {
                return ResourceManager.GetString("WOReportViewModels_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否混包 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_MixType {
            get {
                return ResourceManager.GetString("WOReportViewModels_MixType", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 是否混包 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_ScrapType
        {
            get
            {
                return ResourceManager.GetString("WOReportViewModels_ScrapType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_Note {
            get {
                return ResourceManager.GetString("WOReportViewModels_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_OrderNumber {
            get {
                return ResourceManager.GetString("WOReportViewModels_OrderNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 电流分档 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_PsSubcode
        {
            get
            {
                return ResourceManager.GetString("WOReportViewModels_PsSubcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓库 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_Store {
            get {
                return ResourceManager.GetString("WOReportViewModels_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总数量 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_TotalQty {
            get {
                return ResourceManager.GetString("WOReportViewModels_TotalQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回填的ERP报工单编号 的本地化字符串。
        /// </summary>
        public static string WOReportViewModels_WRCode {
            get {
                return ResourceManager.GetString("WOReportViewModels_WRCode", resourceCulture);
            }
        }

        /// <summary>
        /// 生产车间
        /// </summary>
        public static string WorkOrderViewModel_LocationName
        {
            get
            {
                return ResourceManager.GetString("WorkOrderViewModel_LocationName", resourceCulture);
            }
        }

        /// <summary>
        /// 备注
        /// </summary>
        public static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        /// 入库申报
        /// </summary>
        public static string StockInApply
        {
            get
            {
                return ResourceManager.GetString("StockInApply", resourceCulture);
            }
        }

        /// <summary>
        /// 入库申报撤销成功
        /// </summary>
        public static string WOReport_RevokeStockInApply_Success
        {
            get
            {
                return ResourceManager.GetString("WOReport_RevokeStockInApply_Success", resourceCulture);
            }
        }

        /// <summary>
        /// 入库申报撤销失败
        /// </summary>
        public static string WOReport_RevokeStockInApply_Error
        {
            get
            {
                return ResourceManager.GetString("WOReport_RevokeStockInApply_Error", resourceCulture);
            }
        }

        /// <summary>
        /// 入库接收
        /// </summary>
        public static string StockIn
        {
            get
            {
                return ResourceManager.GetString("StockIn", resourceCulture);
            }
        }

        /// <summary>
        /// ERP入库单主键
        /// </summary>
        public static string WOReportViewModels_ERPStockInKey
        {
            get
            {
                return ResourceManager.GetString("WOReportViewModels_ERPStockInKey", resourceCulture);
            }
        }

        /// <summary>
        /// 撤销入库
        /// </summary>
        public static string RevokeStockIn
        {
            get
            {
                return ResourceManager.GetString("RevokeStockIn", resourceCulture);
            }
        }

        /// <summary>
        /// ERP报工单主键
        /// </summary>
        public static string WOReportViewModels_WRKey
        {
            get
            {
                return ResourceManager.GetString("WOReportViewModels_WRKey", resourceCulture);
            }
        }

        /// <summary>
        /// 入库类型
        /// </summary>
        public static string WOReportViewModels_StockInType
        {
            get
            {
                return ResourceManager.GetString("WOReportViewModels_StockInType", resourceCulture);
            }
        }

        /// <summary>
        /// 在制品入库
        /// </summary>
        public static string ERPWIPStockInTitle
        {
            get
            {
                return ResourceManager.GetString("ERPWIPStockInTitle", resourceCulture);
            }
        }

        /// <summary>
        /// ERP入库单号
        /// </summary>
        public static string WOReportViewModels_ERPStockInCode
        {
            get
            {
                return ResourceManager.GetString("WOReportViewModels_ERPStockInCode", resourceCulture);
            }
        }
    }
}
