//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenter.MES.Service.QAM.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceCenter.MES.Service.QAM.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 检验参数（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string CheckCategoryDetailService_IsExists {
            get {
                return ResourceManager.GetString("CheckCategoryDetailService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验参数（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string CheckCategoryDetailService_IsNotExists {
            get {
                return ResourceManager.GetString("CheckCategoryDetailService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验参数组（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string CheckCategoryService_IsExists {
            get {
                return ResourceManager.GetString("CheckCategoryService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验参数组（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string CheckCategoryService_IsNotExists {
            get {
                return ResourceManager.GetString("CheckCategoryService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验数据明细（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string CheckDataDetailService_IsExists {
            get {
                return ResourceManager.GetString("CheckDataDetailService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验数据明细（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string CheckDataDetailService_IsNotExists {
            get {
                return ResourceManager.GetString("CheckDataDetailService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string CheckDataService_IsExists {
            get {
                return ResourceManager.GetString("CheckDataService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string CheckDataService_IsNotExists {
            get {
                return ResourceManager.GetString("CheckDataService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验计划（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string CheckPlanService_IsExists {
            get {
                return ResourceManager.GetString("CheckPlanService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验计划（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string CheckPlanService_IsNotExists {
            get {
                return ResourceManager.GetString("CheckPlanService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验设置点明细（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string CheckSettingPointDetailService_IsExists {
            get {
                return ResourceManager.GetString("CheckSettingPointDetailService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验设置点明细（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string CheckSettingPointDetailService_IsNotExists {
            get {
                return ResourceManager.GetString("CheckSettingPointDetailService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验设置点（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string CheckSettingPointService_IsExists {
            get {
                return ResourceManager.GetString("CheckSettingPointService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验设置点（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string CheckSettingPointService_IsNotExists {
            get {
                return ResourceManager.GetString("CheckSettingPointService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验设置（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string CheckSettingService_IsExists {
            get {
                return ResourceManager.GetString("CheckSettingService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验设置（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string CheckSettingService_IsNotExists {
            get {
                return ResourceManager.GetString("CheckSettingService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他错误（{0}）。 的本地化字符串。
        /// </summary>
        internal static string OtherError {
            get {
                return ResourceManager.GetString("OtherError", resourceCulture);
            }
        }
    }
}
