//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenter.Client.Mvc.Resources.WIP {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceCenter.Client.Mvc.Resources.WIP.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 属性名称 的本地化字符串。
        /// </summary>
        public static string AttributeName {
            get {
                return ResourceManager.GetString("AttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性值 的本地化字符串。
        /// </summary>
        public static string AttributeValue {
            get {
                return ResourceManager.GetString("AttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成包装 的本地化字符串。
        /// </summary>
        public static string FinishPackage {
            get {
                return ResourceManager.GetString("FinishPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按批次号投料 的本地化字符串。
        /// </summary>
        public static string IsLot {
            get {
                return ResourceManager.GetString("IsLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线别 的本地化字符串。
        /// </summary>
        public static string LineCode {
            get {
                return ResourceManager.GetString("LineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车间 的本地化字符串。
        /// </summary>
        public static string LocationName {
            get {
                return ResourceManager.GetString("LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量批次撤销 的本地化字符串。
        /// </summary>
        public static string LotBatchRevocation_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotBatchRevocation_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动入Bin管理 的本地化字符串。
        /// </summary>
        public static string LotBin_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotBin_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装实时监控 的本地化字符串。
        /// </summary>
        public static string LotBinQuery_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotBinQuery_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转工单作业 的本地化字符串。
        /// </summary>
        public static string LotChange_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotChange_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新产品料号 的本地化字符串。
        /// </summary>
        public static string LotChangeViewModel_NewMaterialCode {
            get {
                return ResourceManager.GetString("LotChangeViewModel_NewMaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新工单号 的本地化字符串。
        /// </summary>
        public static string LotChangeViewModel_NewOrderNumber {
            get {
                return ResourceManager.GetString("LotChangeViewModel_NewOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程组 的本地化字符串。
        /// </summary>
        public static string LotChangeViewModel_RouteEnterpriseName {
            get {
                return ResourceManager.GetString("LotChangeViewModel_RouteEnterpriseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程 的本地化字符串。
        /// </summary>
        public static string LotChangeViewModel_RouteName {
            get {
                return ResourceManager.GetString("LotChangeViewModel_RouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工步 的本地化字符串。
        /// </summary>
        public static string LotChangeViewModel_RouteStepName {
            get {
                return ResourceManager.GetString("LotChangeViewModel_RouteStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建批次 的本地化字符串。
        /// </summary>
        public static string LotCreate_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotCreate_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料数量 的本地化字符串。
        /// </summary>
        public static string LotCreateDetailViewModel_MaterialQty {
            get {
                return ResourceManager.GetString("LotCreateDetailViewModel_MaterialQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品编码 的本地化字符串。
        /// </summary>
        public static string LotCreateDetailViewModel_ProductCode {
            get {
                return ResourceManager.GetString("LotCreateDetailViewModel_ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每批产品数量 的本地化字符串。
        /// </summary>
        public static string LotCreateDetailViewModel_Quantity {
            get {
                return ResourceManager.GetString("LotCreateDetailViewModel_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每批原料数量 的本地化字符串。
        /// </summary>
        public static string LotCreateDetailViewModel_RawQuantity {
            get {
                return ResourceManager.GetString("LotCreateDetailViewModel_RawQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程组 的本地化字符串。
        /// </summary>
        public static string LotCreateDetailViewModel_RouteEnterpriseName {
            get {
                return ResourceManager.GetString("LotCreateDetailViewModel_RouteEnterpriseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程 的本地化字符串。
        /// </summary>
        public static string LotCreateDetailViewModel_RouteName {
            get {
                return ResourceManager.GetString("LotCreateDetailViewModel_RouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺工步 的本地化字符串。
        /// </summary>
        public static string LotCreateDetailViewModel_RouteStepName {
            get {
                return ResourceManager.GetString("LotCreateDetailViewModel_RouteStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商 的本地化字符串。
        /// </summary>
        public static string LotCreateDetailViewModel_SupplierCode {
            get {
                return ResourceManager.GetString("LotCreateDetailViewModel_SupplierCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次个数 的本地化字符串。
        /// </summary>
        public static string LotCreateMainViewModel_Count {
            get {
                return ResourceManager.GetString("LotCreateMainViewModel_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线别 的本地化字符串。
        /// </summary>
        public static string LotCreateMainViewModel_LineCode {
            get {
                return ResourceManager.GetString("LotCreateMainViewModel_LineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓 的本地化字符串。
        /// </summary>
        public static string LotCreateMainViewModel_LineStoreName {
            get {
                return ResourceManager.GetString("LotCreateMainViewModel_LineStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车间 的本地化字符串。
        /// </summary>
        public static string LotCreateMainViewModel_LocationName {
            get {
                return ResourceManager.GetString("LotCreateMainViewModel_LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次产品数量 的本地化字符串。
        /// </summary>
        public static string LotCreateMainViewModel_LotQuantity {
            get {
                return ResourceManager.GetString("LotCreateMainViewModel_LotQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次类型 的本地化字符串。
        /// </summary>
        public static string LotCreateMainViewModel_LotType {
            get {
                return ResourceManager.GetString("LotCreateMainViewModel_LotType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string LotCreateMainViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("LotCreateMainViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料批号 的本地化字符串。
        /// </summary>
        public static string LotCreateMainViewModel_MaterialLot {
            get {
                return ResourceManager.GetString("LotCreateMainViewModel_MaterialLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string LotCreateMainViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("LotCreateMainViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次不良 的本地化字符串。
        /// </summary>
        public static string LotDefect_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotDefect_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不良明细查询 的本地化字符串。
        /// </summary>
        public static string LotDefectQuery_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotDefectQuery_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不良数量 的本地化字符串。
        /// </summary>
        public static string LotDefectViewModel_DefectQuantity {
            get {
                return ResourceManager.GetString("LotDefectViewModel_DefectQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间 的本地化字符串。
        /// </summary>
        public static string LotDefectViewModel_EndTime {
            get {
                return ResourceManager.GetString("LotDefectViewModel_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 责任人 的本地化字符串。
        /// </summary>
        public static string LotDefectViewModel_ResponsiblePerson {
            get {
                return ResourceManager.GetString("LotDefectViewModel_ResponsiblePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 责任工序 的本地化字符串。
        /// </summary>
        public static string LotDefectViewModel_RouteOperationName {
            get {
                return ResourceManager.GetString("LotDefectViewModel_RouteOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序 的本地化字符串。
        /// </summary>
        public static string LotDefectViewModel_RouteStepName {
            get {
                return ResourceManager.GetString("LotDefectViewModel_RouteStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        public static string LotDefectViewModel_StartTime {
            get {
                return ResourceManager.GetString("LotDefectViewModel_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次暂停 的本地化字符串。
        /// </summary>
        public static string LotHold_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotHold_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原因描述 的本地化字符串。
        /// </summary>
        public static string LotHoldViewModel_HoldDescription {
            get {
                return ResourceManager.GetString("LotHoldViewModel_HoldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停密码 的本地化字符串。
        /// </summary>
        public static string LotHoldViewModel_HoldPassword {
            get {
                return ResourceManager.GetString("LotHoldViewModel_HoldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原因组 的本地化字符串。
        /// </summary>
        public static string LotHoldViewModel_ReasonCodeCategoryName {
            get {
                return ResourceManager.GetString("LotHoldViewModel_ReasonCodeCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原因代码 的本地化字符串。
        /// </summary>
        public static string LotHoldViewModel_ReasonCodeName {
            get {
                return ResourceManager.GetString("LotHoldViewModel_ReasonCodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次号（{0}）不存在。 的本地化字符串。
        /// </summary>
        public static string LotIsNotExists {
            get {
                return ResourceManager.GetString("LotIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组件匹配优化器作业 的本地化字符串。
        /// </summary>
        public static string LotMateSemodules_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotMateSemodules_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次号 的本地化字符串。
        /// </summary>
        public static string LotNumber {
            get {
                return ResourceManager.GetString("LotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装作业 的本地化字符串。
        /// </summary>
        public static string LotPackage_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotPackage_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前数量 的本地化字符串。
        /// </summary>
        public static string LotPackageViewModel_CurrentQuantity {
            get {
                return ResourceManager.GetString("LotPackageViewModel_CurrentQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备 的本地化字符串。
        /// </summary>
        public static string LotPackageViewModel_EquipmentCode {
            get {
                return ResourceManager.GetString("LotPackageViewModel_EquipmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备状态 的本地化字符串。
        /// </summary>
        public static string LotPackageViewModel_EquipmentState {
            get {
                return ResourceManager.GetString("LotPackageViewModel_EquipmentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 满包数量 的本地化字符串。
        /// </summary>
        public static string LotPackageViewModel_FullQuantity {
            get {
                return ResourceManager.GetString("LotPackageViewModel_FullQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾包？ 的本地化字符串。
        /// </summary>
        public static string LotPackageViewModel_IsLastestPackage {
            get {
                return ResourceManager.GetString("LotPackageViewModel_IsLastestPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产线 的本地化字符串。
        /// </summary>
        public static string LotPackageViewModel_LineCode {
            get {
                return ResourceManager.GetString("LotPackageViewModel_LineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序名称 的本地化字符串。
        /// </summary>
        public static string LotPackageViewModel_RouteOperationName {
            get {
                return ResourceManager.GetString("LotPackageViewModel_RouteOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次补料 的本地化字符串。
        /// </summary>
        public static string LotPatch_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotPatch_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 补料明细查询 的本地化字符串。
        /// </summary>
        public static string LotPatchQuery_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotPatchQuery_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 补料时间 的本地化字符串。
        /// </summary>
        public static string LotPatchViewModel_EndPatchTime {
            get {
                return ResourceManager.GetString("LotPatchViewModel_EndPatchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线别 的本地化字符串。
        /// </summary>
        public static string LotPatchViewModel_LineCode {
            get {
                return ResourceManager.GetString("LotPatchViewModel_LineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓 的本地化字符串。
        /// </summary>
        public static string LotPatchViewModel_LineStoreName {
            get {
                return ResourceManager.GetString("LotPatchViewModel_LineStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string LotPatchViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("LotPatchViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料批号 的本地化字符串。
        /// </summary>
        public static string LotPatchViewModel_MaterialLot {
            get {
                return ResourceManager.GetString("LotPatchViewModel_MaterialLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string LotPatchViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("LotPatchViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 补片数量 的本地化字符串。
        /// </summary>
        public static string LotPatchViewModel_PatchQuantity {
            get {
                return ResourceManager.GetString("LotPatchViewModel_PatchQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 责任人 的本地化字符串。
        /// </summary>
        public static string LotPatchViewModel_ResponsiblePerson {
            get {
                return ResourceManager.GetString("LotPatchViewModel_ResponsiblePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 责任工序 的本地化字符串。
        /// </summary>
        public static string LotPatchViewModel_RouteOperationName {
            get {
                return ResourceManager.GetString("LotPatchViewModel_RouteOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 补料时间 的本地化字符串。
        /// </summary>
        public static string LotPatchViewModel_StartPatchTime {
            get {
                return ResourceManager.GetString("LotPatchViewModel_StartPatchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次标签打印 的本地化字符串。
        /// </summary>
        public static string LotPrint_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotPrint_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印机名称 的本地化字符串。
        /// </summary>
        public static string LotPrintViewModel_PrinterName {
            get {
                return ResourceManager.GetString("LotPrintViewModel_PrinterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印标签 的本地化字符串。
        /// </summary>
        public static string LotPrintViewModel_PrintLabelCode {
            get {
                return ResourceManager.GetString("LotPrintViewModel_PrintLabelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印数量 的本地化字符串。
        /// </summary>
        public static string LotPrintViewModel_PrintQty {
            get {
                return ResourceManager.GetString("LotPrintViewModel_PrintQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次查询 的本地化字符串。
        /// </summary>
        public static string LotQuery_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotQuery_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次释放 的本地化字符串。
        /// </summary>
        public static string LotRelease_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotRelease_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原因描述 的本地化字符串。
        /// </summary>
        public static string LotReleaseViewModel_ReleaseDescription {
            get {
                return ResourceManager.GetString("LotReleaseViewModel_ReleaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 释放密码 的本地化字符串。
        /// </summary>
        public static string LotReleaseViewModel_ReleasePassword {
            get {
                return ResourceManager.GetString("LotReleaseViewModel_ReleasePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次返修 的本地化字符串。
        /// </summary>
        public static string LotRepair_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotRepair_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次退料 的本地化字符串。
        /// </summary>
        public static string LotReturn_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotReturn_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退料数量 的本地化字符串。
        /// </summary>
        public static string LotReturnViewModel_ReturnQuantity {
            get {
                return ResourceManager.GetString("LotReturnViewModel_ReturnQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返工作业 的本地化字符串。
        /// </summary>
        public static string LotRework_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotRework_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按包返工？ 的本地化字符串。
        /// </summary>
        public static string LotReworkViewModel_IsPackageNo {
            get {
                return ResourceManager.GetString("LotReworkViewModel_IsPackageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新产品料号 的本地化字符串。
        /// </summary>
        public static string LotReworkViewModel_NewMaterialCode {
            get {
                return ResourceManager.GetString("LotReworkViewModel_NewMaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新工单号 的本地化字符串。
        /// </summary>
        public static string LotReworkViewModel_NewOrderNumber {
            get {
                return ResourceManager.GetString("LotReworkViewModel_NewOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程组 的本地化字符串。
        /// </summary>
        public static string LotReworkViewModel_RouteEnterpriseName {
            get {
                return ResourceManager.GetString("LotReworkViewModel_RouteEnterpriseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程 的本地化字符串。
        /// </summary>
        public static string LotReworkViewModel_RouteName {
            get {
                return ResourceManager.GetString("LotReworkViewModel_RouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工步 的本地化字符串。
        /// </summary>
        public static string LotReworkViewModel_RouteStepName {
            get {
                return ResourceManager.GetString("LotReworkViewModel_RouteStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次报废 的本地化字符串。
        /// </summary>
        public static string LotScrap_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotScrap_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报废明细查询 的本地化字符串。
        /// </summary>
        public static string LotScrapQuery_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotScrapQuery_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 责任人 的本地化字符串。
        /// </summary>
        public static string LotScrapViewModel_ResponsiblePerson {
            get {
                return ResourceManager.GetString("LotScrapViewModel_ResponsiblePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 责任工序 的本地化字符串。
        /// </summary>
        public static string LotScrapViewModel_RouteOperationName {
            get {
                return ResourceManager.GetString("LotScrapViewModel_RouteOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报废数量 的本地化字符串。
        /// </summary>
        public static string LotScrapViewModel_ScrapQuantity {
            get {
                return ResourceManager.GetString("LotScrapViewModel_ScrapQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次结束 的本地化字符串。
        /// </summary>
        public static string LotTerminal_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotTerminal_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原因组 的本地化字符串。
        /// </summary>
        public static string LotTerminalViewModel_ReasonCodeCategoryName {
            get {
                return ResourceManager.GetString("LotTerminalViewModel_ReasonCodeCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原因代码 的本地化字符串。
        /// </summary>
        public static string LotTerminalViewModel_ReasonCodeName {
            get {
                return ResourceManager.GetString("LotTerminalViewModel_ReasonCodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作站作业 的本地化字符串。
        /// </summary>
        public static string LotTrack_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotTrack_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string LotTrackMaterialViewModel_LoadingQty {
            get {
                return ResourceManager.GetString("LotTrackMaterialViewModel_LoadingQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料 的本地化字符串。
        /// </summary>
        public static string LotTrackMaterialViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("LotTrackMaterialViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料批次 的本地化字符串。
        /// </summary>
        public static string LotTrackMaterialViewModel_MaterialLot {
            get {
                return ResourceManager.GetString("LotTrackMaterialViewModel_MaterialLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料名称 的本地化字符串。
        /// </summary>
        public static string LotTrackMaterialViewModel_MaterialName {
            get {
                return ResourceManager.GetString("LotTrackMaterialViewModel_MaterialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string LotTrackMaterialViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("LotTrackMaterialViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程 的本地化字符串。
        /// </summary>
        public static string LotTrackMaterialViewModel_RouteName {
            get {
                return ResourceManager.GetString("LotTrackMaterialViewModel_RouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备 的本地化字符串。
        /// </summary>
        public static string LotTrackViewModel_EquipmentCode {
            get {
                return ResourceManager.GetString("LotTrackViewModel_EquipmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备状态 的本地化字符串。
        /// </summary>
        public static string LotTrackViewModel_EquipmentState {
            get {
                return ResourceManager.GetString("LotTrackViewModel_EquipmentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产线 的本地化字符串。
        /// </summary>
        public static string LotTrackViewModel_LineCode {
            get {
                return ResourceManager.GetString("LotTrackViewModel_LineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程 的本地化字符串。
        /// </summary>
        public static string LotTrackViewModel_RouteName {
            get {
                return ResourceManager.GetString("LotTrackViewModel_RouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序名称 的本地化字符串。
        /// </summary>
        public static string LotTrackViewModel_RouteOperationName {
            get {
                return ResourceManager.GetString("LotTrackViewModel_RouteOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次撤销 的本地化字符串。
        /// </summary>
        public static string LotUndo_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotUndo_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验条码1 的本地化字符串。
        /// </summary>
        public static string LotViewModel_Barcode1 {
            get {
                return ResourceManager.GetString("LotViewModel_Barcode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验条码2 的本地化字符串。
        /// </summary>
        public static string LotViewModel_Barcode2 {
            get {
                return ResourceManager.GetString("LotViewModel_Barcode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验条码AA 的本地化字符串。
        /// </summary>
        public static string LotViewModel_BarcodeAA {
            get {
                return ResourceManager.GetString("LotViewModel_BarcodeAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验条码AB 的本地化字符串。
        /// </summary>
        public static string LotViewModel_BarcodeAB {
            get {
                return ResourceManager.GetString("LotViewModel_BarcodeAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验条码AC 的本地化字符串。
        /// </summary>
        public static string LotViewModel_BarcodeAC {
            get {
                return ResourceManager.GetString("LotViewModel_BarcodeAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验条码BA 的本地化字符串。
        /// </summary>
        public static string LotViewModel_BarcodeBA {
            get {
                return ResourceManager.GetString("LotViewModel_BarcodeBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验条码BB 的本地化字符串。
        /// </summary>
        public static string LotViewModel_BarcodeBB {
            get {
                return ResourceManager.GetString("LotViewModel_BarcodeBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验条码BC 的本地化字符串。
        /// </summary>
        public static string LotViewModel_BarcodeBC {
            get {
                return ResourceManager.GetString("LotViewModel_BarcodeBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 花色 的本地化字符串。
        /// </summary>
        public static string LotViewModel_Color {
            get {
                return ResourceManager.GetString("LotViewModel_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 容器号 的本地化字符串。
        /// </summary>
        public static string LotViewModel_ContainerNo {
            get {
                return ResourceManager.GetString("LotViewModel_ContainerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束？ 的本地化字符串。
        /// </summary>
        public static string LotViewModel_DeletedFlag {
            get {
                return ResourceManager.GetString("LotViewModel_DeletedFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string LotViewModel_Description {
            get {
                return ResourceManager.GetString("LotViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间（止） 的本地化字符串。
        /// </summary>
        public static string LotViewModel_EndCreateTime {
            get {
                return ResourceManager.GetString("LotViewModel_EndCreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备代码 的本地化字符串。
        /// </summary>
        public static string LotViewModel_EquipmentCode {
            get {
                return ResourceManager.GetString("LotViewModel_EquipmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等级 的本地化字符串。
        /// </summary>
        public static string LotViewModel_Grade {
            get {
                return ResourceManager.GetString("LotViewModel_Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停？ 的本地化字符串。
        /// </summary>
        public static string LotViewModel_HoldFlag {
            get {
                return ResourceManager.GetString("LotViewModel_HoldFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始数量 的本地化字符串。
        /// </summary>
        public static string LotViewModel_InitialQuantity {
            get {
                return ResourceManager.GetString("LotViewModel_InitialQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 层压机设备号 的本地化字符串。
        /// </summary>
        public static string LotViewModel_LayerEquipmentNo {
            get {
                return ResourceManager.GetString("LotViewModel_LayerEquipmentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产线 的本地化字符串。
        /// </summary>
        public static string LotViewModel_LineCode {
            get {
                return ResourceManager.GetString("LotViewModel_LineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车间名称 的本地化字符串。
        /// </summary>
        public static string LotViewModel_LocationName {
            get {
                return ResourceManager.GetString("LotViewModel_LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次状态 的本地化字符串。
        /// </summary>
        public static string LotViewModel_LotState {
            get {
                return ResourceManager.GetString("LotViewModel_LotState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次类型 的本地化字符串。
        /// </summary>
        public static string LotViewModel_LotType {
            get {
                return ResourceManager.GetString("LotViewModel_LotType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品编码 的本地化字符串。
        /// </summary>
        public static string LotViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("LotViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作客户端 的本地化字符串。
        /// </summary>
        public static string LotViewModel_OperateComputer {
            get {
                return ResourceManager.GetString("LotViewModel_OperateComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string LotViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("LotViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始工单号 的本地化字符串。
        /// </summary>
        public static string LotViewModel_OriginalOrderNumber {
            get {
                return ResourceManager.GetString("LotViewModel_OriginalOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装？ 的本地化字符串。
        /// </summary>
        public static string LotViewModel_PackageFlag {
            get {
                return ResourceManager.GetString("LotViewModel_PackageFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装号 的本地化字符串。
        /// </summary>
        public static string LotViewModel_PackageNo {
            get {
                return ResourceManager.GetString("LotViewModel_PackageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前一生产线 的本地化字符串。
        /// </summary>
        public static string LotViewModel_PreLineCode {
            get {
                return ResourceManager.GetString("LotViewModel_PreLineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优先级 的本地化字符串。
        /// </summary>
        public static string LotViewModel_Priority {
            get {
                return ResourceManager.GetString("LotViewModel_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string LotViewModel_Quantity {
            get {
                return ResourceManager.GetString("LotViewModel_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返修次数 的本地化字符串。
        /// </summary>
        public static string LotViewModel_RepairFlag {
            get {
                return ResourceManager.GetString("LotViewModel_RepairFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返工操作人 的本地化字符串。
        /// </summary>
        public static string LotViewModel_Reworker {
            get {
                return ResourceManager.GetString("LotViewModel_Reworker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返工次数 的本地化字符串。
        /// </summary>
        public static string LotViewModel_ReworkFlag {
            get {
                return ResourceManager.GetString("LotViewModel_ReworkFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返工时间 的本地化字符串。
        /// </summary>
        public static string LotViewModel_ReworkTime {
            get {
                return ResourceManager.GetString("LotViewModel_ReworkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程组 的本地化字符串。
        /// </summary>
        public static string LotViewModel_RouteEnterpriseName {
            get {
                return ResourceManager.GetString("LotViewModel_RouteEnterpriseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程 的本地化字符串。
        /// </summary>
        public static string LotViewModel_RouteName {
            get {
                return ResourceManager.GetString("LotViewModel_RouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺工步 的本地化字符串。
        /// </summary>
        public static string LotViewModel_RouteStepName {
            get {
                return ResourceManager.GetString("LotViewModel_RouteStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出货？ 的本地化字符串。
        /// </summary>
        public static string LotViewModel_ShippedFlag {
            get {
                return ResourceManager.GetString("LotViewModel_ShippedFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装护角 的本地化字符串。
        /// </summary>
        public static string LotViewModel_ShowDialog {
            get {
                return ResourceManager.GetString("LotViewModel_ShowDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间（起） 的本地化字符串。
        /// </summary>
        public static string LotViewModel_StartCreateTime {
            get {
                return ResourceManager.GetString("LotViewModel_StartCreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始处理时间 的本地化字符串。
        /// </summary>
        public static string LotViewModel_StartProcessTime {
            get {
                return ResourceManager.GetString("LotViewModel_StartProcessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始等待时间 的本地化字符串。
        /// </summary>
        public static string LotViewModel_StartWaitTime {
            get {
                return ResourceManager.GetString("LotViewModel_StartWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次状态 的本地化字符串。
        /// </summary>
        public static string LotViewModel_StateFlag {
            get {
                return ResourceManager.GetString("LotViewModel_StateFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配 的本地化字符串。
        /// </summary>
        public static string Mate {
            get {
                return ResourceManager.GetString("Mate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OEM数据查询 的本地化字符串。
        /// </summary>
        public static string OemDataQuery_ManagePageTitle {
            get {
                return ResourceManager.GetString("OemDataQuery_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 花色 的本地化字符串。
        /// </summary>
        public static string OemDataViewModel_Color {
            get {
                return ResourceManager.GetString("OemDataViewModel_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等级 的本地化字符串。
        /// </summary>
        public static string OemDataViewModel_Grade {
            get {
                return ResourceManager.GetString("OemDataViewModel_Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次号 的本地化字符串。
        /// </summary>
        public static string OemDataViewModel_LotNumber {
            get {
                return ResourceManager.GetString("OemDataViewModel_LotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string OemDataViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("OemDataViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装号 的本地化字符串。
        /// </summary>
        public static string OemDataViewModel_PackageNo {
            get {
                return ResourceManager.GetString("OemDataViewModel_PackageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功率档 的本地化字符串。
        /// </summary>
        public static string OemDataViewModel_PnName {
            get {
                return ResourceManager.GetString("OemDataViewModel_PnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电流档 的本地化字符串。
        /// </summary>
        public static string OemDataViewModel_PsSubCode {
            get {
                return ResourceManager.GetString("OemDataViewModel_PsSubCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次状态 的本地化字符串。
        /// </summary>
        public static string OemDataViewModel_Status {
            get {
                return ResourceManager.GetString("OemDataViewModel_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装 的本地化字符串。
        /// </summary>
        public static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除（{0}）? 的本地化字符串。
        /// </summary>
        public static string PackageDetail_ConfirmDelete {
            get {
                return ResourceManager.GetString("PackageDetail_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装号 的本地化字符串。
        /// </summary>
        public static string PackageNo {
            get {
                return ResourceManager.GetString("PackageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装标签打印 的本地化字符串。
        /// </summary>
        public static string PackagePrint_ManagePageTitle {
            get {
                return ResourceManager.GetString("PackagePrint_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印机名称 的本地化字符串。
        /// </summary>
        public static string PackagePrintViewModel_PrinterName {
            get {
                return ResourceManager.GetString("PackagePrintViewModel_PrinterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签代码 的本地化字符串。
        /// </summary>
        public static string PackagePrintViewModel_PrintLabelCode {
            get {
                return ResourceManager.GetString("PackagePrintViewModel_PrintLabelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印数量 的本地化字符串。
        /// </summary>
        public static string PackagePrintViewModel_PrintQty {
            get {
                return ResourceManager.GetString("PackagePrintViewModel_PrintQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投料作业 的本地化字符串。
        /// </summary>
        public static string PackageRework_ManagePageTitle {
            get {
                return ResourceManager.GetString("PackageRework_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程 的本地化字符串。
        /// </summary>
        public static string PackageReworkViewModel_RouteName {
            get {
                return ResourceManager.GetString("PackageReworkViewModel_RouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工步 的本地化字符串。
        /// </summary>
        public static string PackageReworkViewModel_RouteStepName {
            get {
                return ResourceManager.GetString("PackageReworkViewModel_RouteStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原因组 的本地化字符串。
        /// </summary>
        public static string ReasonCodeCategoryName {
            get {
                return ResourceManager.GetString("ReasonCodeCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原因代码 的本地化字符串。
        /// </summary>
        public static string ReasonCodeName {
            get {
                return ResourceManager.GetString("ReasonCodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原因描述 的本地化字符串。
        /// </summary>
        public static string ReasonDescription {
            get {
                return ResourceManager.GetString("ReasonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保留托号 的本地化字符串。
        /// </summary>
        public static string RetainPackageNo {
            get {
                return ResourceManager.GetString("RetainPackageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优化器编号 的本地化字符串。
        /// </summary>
        public static string SEModulesNo {
            get {
                return ResourceManager.GetString("SEModulesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过站 的本地化字符串。
        /// </summary>
        public static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定撤销 的本地化字符串。
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销包装护角 的本地化字符串。
        /// </summary>
        public static string UndoPackageCorner {
            get {
                return ResourceManager.GetString("UndoPackageCorner", resourceCulture);
            }
        }
    }
}
