//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenter.Client.Mvc.Resources.PPM {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceCenter.Client.Mvc.Resources.PPM.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新增工单 的本地化字符串。
        /// </summary>
        public static string WorkOrder_AddTitle {
            get {
                return ResourceManager.GetString("WorkOrder_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除工单 ( {0}） ？ 的本地化字符串。
        /// </summary>
        public static string WorkOrder_ConfirmDelete {
            get {
                return ResourceManager.GetString("WorkOrder_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除工单  {0}  成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrder_Delete_Success {
            get {
                return ResourceManager.GetString("WorkOrder_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单信息 的本地化字符串。
        /// </summary>
        public static string WorkOrder_DetailTitle {
            get {
                return ResourceManager.GetString("WorkOrder_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单管理 的本地化字符串。
        /// </summary>
        public static string WorkOrder_ManagePageTitle {
            get {
                return ResourceManager.GetString("WorkOrder_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单 的本地化字符串。
        /// </summary>
        public static string WorkOrder_ModifyTitle {
            get {
                return ResourceManager.GetString("WorkOrder_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存工单 {0} 成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrder_Save_Success {
            get {
                return ResourceManager.GetString("WorkOrder_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单 {0} 成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrder_SaveModify_Success {
            get {
                return ResourceManager.GetString("WorkOrder_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置线别 的本地化字符串。
        /// </summary>
        public static string WorkOrder_SettingLine {
            get {
                return ResourceManager.GetString("WorkOrder_SettingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品维护 的本地化字符串。
        /// </summary>
        public static string WorkOrder_SettingProduct {
            get {
                return ResourceManager.GetString("WorkOrder_SettingProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置工艺 的本地化字符串。
        /// </summary>
        public static string WorkOrder_SettingRoute {
            get {
                return ResourceManager.GetString("WorkOrder_SettingRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增工单属性值 的本地化字符串。
        /// </summary>
        public static string WorkOrderAttribute_AddTitle {
            get {
                return ResourceManager.GetString("WorkOrderAttribute_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除工单属性 ( {0}）值 ？ 的本地化字符串。
        /// </summary>
        public static string WorkOrderAttribute_ConfirmDelete {
            get {
                return ResourceManager.GetString("WorkOrderAttribute_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除工单属性  {0} 值成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderAttribute_Delete_Success {
            get {
                return ResourceManager.GetString("WorkOrderAttribute_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单属性值信息 的本地化字符串。
        /// </summary>
        public static string WorkOrderAttribute_DetailTitle {
            get {
                return ResourceManager.GetString("WorkOrderAttribute_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单（{0}）属性值管理 的本地化字符串。
        /// </summary>
        public static string WorkOrderAttribute_ManagePageTitle {
            get {
                return ResourceManager.GetString("WorkOrderAttribute_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单属性值 的本地化字符串。
        /// </summary>
        public static string WorkOrderAttribute_ModifyTitle {
            get {
                return ResourceManager.GetString("WorkOrderAttribute_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存工单属性 {0} 值成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderAttribute_Save_Success {
            get {
                return ResourceManager.GetString("WorkOrderAttribute_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单属性 {0} 值成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderAttribute_SaveModify_Success {
            get {
                return ResourceManager.GetString("WorkOrderAttribute_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性名 的本地化字符串。
        /// </summary>
        public static string WorkOrderAttributeQueryViewModel_AttributeName {
            get {
                return ResourceManager.GetString("WorkOrderAttributeQueryViewModel_AttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string WorkOrderAttributeQueryViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderAttributeQueryViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性名 的本地化字符串。
        /// </summary>
        public static string WorkOrderAttributeViewModel_AttributeName {
            get {
                return ResourceManager.GetString("WorkOrderAttributeViewModel_AttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string WorkOrderAttributeViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderAttributeViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性值 的本地化字符串。
        /// </summary>
        public static string WorkOrderAttributeViewModel_Value {
            get {
                return ResourceManager.GetString("WorkOrderAttributeViewModel_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增工单BOM 的本地化字符串。
        /// </summary>
        public static string WorkOrderBOM_AddTitle {
            get {
                return ResourceManager.GetString("WorkOrderBOM_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除工单BOM ( {0}） ？ 的本地化字符串。
        /// </summary>
        public static string WorkOrderBOM_ConfirmDelete {
            get {
                return ResourceManager.GetString("WorkOrderBOM_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除工单BOM  {0} 成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderBOM_Delete_Success {
            get {
                return ResourceManager.GetString("WorkOrderBOM_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单BOM信息 的本地化字符串。
        /// </summary>
        public static string WorkOrderBOM_DetailTitle {
            get {
                return ResourceManager.GetString("WorkOrderBOM_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单（{0}）BOM管理 的本地化字符串。
        /// </summary>
        public static string WorkOrderBOM_ManagePageTitle {
            get {
                return ResourceManager.GetString("WorkOrderBOM_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单BOM 的本地化字符串。
        /// </summary>
        public static string WorkOrderBOM_ModifyTitle {
            get {
                return ResourceManager.GetString("WorkOrderBOM_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存工单BOM {0} 成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderBOM_Save_Success {
            get {
                return ResourceManager.GetString("WorkOrderBOM_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单BOM {0} 成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderBOM_SaveModify_Success {
            get {
                return ResourceManager.GetString("WorkOrderBOM_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string WorkOrderBOMQueryViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("WorkOrderBOMQueryViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string WorkOrderBOMQueryViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderBOMQueryViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目号 的本地化字符串。
        /// </summary>
        public static string WorkOrderBOMViewModel_ItemNo {
            get {
                return ResourceManager.GetString("WorkOrderBOMViewModel_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string WorkOrderBOMViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("WorkOrderBOMViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位 的本地化字符串。
        /// </summary>
        public static string WorkOrderBOMViewModel_MaterialUnit {
            get {
                return ResourceManager.GetString("WorkOrderBOMViewModel_MaterialUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string WorkOrderBOMViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderBOMViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string WorkOrderBOMViewModel_Qty {
            get {
                return ResourceManager.GetString("WorkOrderBOMViewModel_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储位置 的本地化字符串。
        /// </summary>
        public static string WorkOrderBOMViewModel_StoreLocation {
            get {
                return ResourceManager.GetString("WorkOrderBOMViewModel_StoreLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作中心 的本地化字符串。
        /// </summary>
        public static string WorkOrderBOMViewModel_WorkCenter {
            get {
                return ResourceManager.GetString("WorkOrderBOMViewModel_WorkCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增工单产品 的本地化字符串。
        /// </summary>
        public static string WorkOrderProduct_AddTitle {
            get {
                return ResourceManager.GetString("WorkOrderProduct_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除工单产品 ( {0}） ？ 的本地化字符串。
        /// </summary>
        public static string WorkOrderProduct_ConfirmDelete {
            get {
                return ResourceManager.GetString("WorkOrderProduct_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除工单产品  {0} 成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderProduct_Delete_Success {
            get {
                return ResourceManager.GetString("WorkOrderProduct_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单产品信息 的本地化字符串。
        /// </summary>
        public static string WorkOrderProduct_DetailTitle {
            get {
                return ResourceManager.GetString("WorkOrderProduct_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单（{0}）产品管理 的本地化字符串。
        /// </summary>
        public static string WorkOrderProduct_ManagePageTitle {
            get {
                return ResourceManager.GetString("WorkOrderProduct_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单产品 的本地化字符串。
        /// </summary>
        public static string WorkOrderProduct_ModifyTitle {
            get {
                return ResourceManager.GetString("WorkOrderProduct_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存工单产品 {0} 成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderProduct_Save_Success {
            get {
                return ResourceManager.GetString("WorkOrderProduct_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单产品 {0} 成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderProduct_SaveModify_Success {
            get {
                return ResourceManager.GetString("WorkOrderProduct_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增线别代码 的本地化字符串。
        /// </summary>
        public static string WorkOrderProductionLine_AddTitle {
            get {
                return ResourceManager.GetString("WorkOrderProductionLine_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除线别代码 ( {0}） ？ 的本地化字符串。
        /// </summary>
        public static string WorkOrderProductionLine_ConfirmDelete {
            get {
                return ResourceManager.GetString("WorkOrderProductionLine_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除线别代码  {0} 成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderProductionLine_Delete_Success {
            get {
                return ResourceManager.GetString("WorkOrderProductionLine_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线别名称 的本地化字符串。
        /// </summary>
        public static string WorkOrderProductionLine_LineName {
            get {
                return ResourceManager.GetString("WorkOrderProductionLine_LineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置工单（{0}）线别 的本地化字符串。
        /// </summary>
        public static string WorkOrderProductionLine_ManagePageTitle {
            get {
                return ResourceManager.GetString("WorkOrderProductionLine_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存工单线别 {0} 成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderProductionLine_Save_Success {
            get {
                return ResourceManager.GetString("WorkOrderProductionLine_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线别代码 的本地化字符串。
        /// </summary>
        public static string WorkOrderProductionLineQueryViewModel_LineCode {
            get {
                return ResourceManager.GetString("WorkOrderProductionLineQueryViewModel_LineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string WorkOrderProductionLineQueryViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderProductionLineQueryViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线别代码 的本地化字符串。
        /// </summary>
        public static string WorkOrderProductionLineViewModel_LineCode {
            get {
                return ResourceManager.GetString("WorkOrderProductionLineViewModel_LineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string WorkOrderProductionLineViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderProductionLineViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主产品？ 的本地化字符串。
        /// </summary>
        public static string WorkOrderProductQueryViewModel_IsMain {
            get {
                return ResourceManager.GetString("WorkOrderProductQueryViewModel_IsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目号 的本地化字符串。
        /// </summary>
        public static string WorkOrderProductQueryViewModel_ItemNo {
            get {
                return ResourceManager.GetString("WorkOrderProductQueryViewModel_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品编码 的本地化字符串。
        /// </summary>
        public static string WorkOrderProductQueryViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("WorkOrderProductQueryViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string WorkOrderProductQueryViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderProductQueryViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string WorkOrderProductViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("WorkOrderProductViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string WorkOrderProductViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderProductViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string WorkOrderQueryViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderQueryViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增工艺路线 的本地化字符串。
        /// </summary>
        public static string WorkOrderRoute_AddTitle {
            get {
                return ResourceManager.GetString("WorkOrderRoute_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除工艺路线 ( {0}） ？ 的本地化字符串。
        /// </summary>
        public static string WorkOrderRoute_ConfirmDelete {
            get {
                return ResourceManager.GetString("WorkOrderRoute_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除工艺路线  {0} 成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderRoute_Delete_Success {
            get {
                return ResourceManager.GetString("WorkOrderRoute_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺路线信息 的本地化字符串。
        /// </summary>
        public static string WorkOrderRoute_DetailTitle {
            get {
                return ResourceManager.GetString("WorkOrderRoute_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单（{0}）工艺路线设置 的本地化字符串。
        /// </summary>
        public static string WorkOrderRoute_ManagePageTitle {
            get {
                return ResourceManager.GetString("WorkOrderRoute_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工艺路线 的本地化字符串。
        /// </summary>
        public static string WorkOrderRoute_ModifyTitle {
            get {
                return ResourceManager.GetString("WorkOrderRoute_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存工艺路线 {0} 成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderRoute_Save_Success {
            get {
                return ResourceManager.GetString("WorkOrderRoute_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工艺路线 {0} 成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderRoute_SaveModify_Success {
            get {
                return ResourceManager.GetString("WorkOrderRoute_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string WorkOrderRouteQueryViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderRouteQueryViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返工/返修？ 的本地化字符串。
        /// </summary>
        public static string WorkOrderRouteViewModel_IsRework {
            get {
                return ResourceManager.GetString("WorkOrderRouteViewModel_IsRework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目号 的本地化字符串。
        /// </summary>
        public static string WorkOrderRouteViewModel_ItemNo {
            get {
                return ResourceManager.GetString("WorkOrderRouteViewModel_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string WorkOrderRouteViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderRouteViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程组 的本地化字符串。
        /// </summary>
        public static string WorkOrderRouteViewModel_RouteEnterpriseName {
            get {
                return ResourceManager.GetString("WorkOrderRouteViewModel_RouteEnterpriseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程 的本地化字符串。
        /// </summary>
        public static string WorkOrderRouteViewModel_RouteName {
            get {
                return ResourceManager.GetString("WorkOrderRouteViewModel_RouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺工步 的本地化字符串。
        /// </summary>
        public static string WorkOrderRouteViewModel_RouteStepName {
            get {
                return ResourceManager.GetString("WorkOrderRouteViewModel_RouteStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭类型 的本地化字符串。
        /// </summary>
        public static string WorkOrderViewModel_CloseType {
            get {
                return ResourceManager.GetString("WorkOrderViewModel_CloseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完工数量 的本地化字符串。
        /// </summary>
        public static string WorkOrderViewModel_FinishQuantity {
            get {
                return ResourceManager.GetString("WorkOrderViewModel_FinishQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完工时间 的本地化字符串。
        /// </summary>
        public static string WorkOrderViewModel_FinishTime {
            get {
                return ResourceManager.GetString("WorkOrderViewModel_FinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余数量 的本地化字符串。
        /// </summary>
        public static string WorkOrderViewModel_LeftQuantity {
            get {
                return ResourceManager.GetString("WorkOrderViewModel_LeftQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车间名称 的本地化字符串。
        /// </summary>
        public static string WorkOrderViewModel_LocationName {
            get {
                return ResourceManager.GetString("WorkOrderViewModel_LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品编码 的本地化字符串。
        /// </summary>
        public static string WorkOrderViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("WorkOrderViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string WorkOrderViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划数量 的本地化字符串。
        /// </summary>
        public static string WorkOrderViewModel_OrderQuantity {
            get {
                return ResourceManager.GetString("WorkOrderViewModel_OrderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单状态 的本地化字符串。
        /// </summary>
        public static string WorkOrderViewModel_OrderState {
            get {
                return ResourceManager.GetString("WorkOrderViewModel_OrderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单类型 的本地化字符串。
        /// </summary>
        public static string WorkOrderViewModel_OrderType {
            get {
                return ResourceManager.GetString("WorkOrderViewModel_OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优先级 的本地化字符串。
        /// </summary>
        public static string WorkOrderViewModel_Priority {
            get {
                return ResourceManager.GetString("WorkOrderViewModel_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返修数量 的本地化字符串。
        /// </summary>
        public static string WorkOrderViewModel_RepairQuantity {
            get {
                return ResourceManager.GetString("WorkOrderViewModel_RepairQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保税类型 的本地化字符串。
        /// </summary>
        public static string WorkOrderViewModel_RevenueType {
            get {
                return ResourceManager.GetString("WorkOrderViewModel_RevenueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返工数量 的本地化字符串。
        /// </summary>
        public static string WorkOrderViewModel_ReworkQuantity {
            get {
                return ResourceManager.GetString("WorkOrderViewModel_ReworkQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报废数量 的本地化字符串。
        /// </summary>
        public static string WorkOrderViewModel_ScrapQuantity {
            get {
                return ResourceManager.GetString("WorkOrderViewModel_ScrapQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        public static string WorkOrderViewModel_StartTime {
            get {
                return ResourceManager.GetString("WorkOrderViewModel_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在制品数量 的本地化字符串。
        /// </summary>
        public static string WorkOrderViewModel_WIPQuantity {
            get {
                return ResourceManager.GetString("WorkOrderViewModel_WIPQuantity", resourceCulture);
            }
        }
    }
}
