//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenter.MES.Service.RBAC.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceCenter.MES.Service.RBAC.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 资源（{0}:{1}）已存在。 的本地化字符串。
        /// </summary>
        internal static string ResourceService_IsExists {
            get {
                return ResourceManager.GetString("ResourceService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源（{0}:{1}）不存在。 的本地化字符串。
        /// </summary>
        internal static string ResourceService_IsNotExists {
            get {
                return ResourceManager.GetString("ResourceService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他错误：（{0}） 的本地化字符串。
        /// </summary>
        internal static string ResourceService_OtherError {
            get {
                return ResourceManager.GetString("ResourceService_OtherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色资源（{0}-{1}:{2}）已存在。 的本地化字符串。
        /// </summary>
        internal static string RoleOwnResourceService_IsExists {
            get {
                return ResourceManager.GetString("RoleOwnResourceService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色资源（{0}-{1}:{2}）不存在。 的本地化字符串。
        /// </summary>
        internal static string RoleOwnResourceService_IsNotExists {
            get {
                return ResourceManager.GetString("RoleOwnResourceService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他错误：（{0}） 的本地化字符串。
        /// </summary>
        internal static string RoleOwnResourceService_OtherError {
            get {
                return ResourceManager.GetString("RoleOwnResourceService_OtherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string RoleService_IsExists {
            get {
                return ResourceManager.GetString("RoleService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string RoleService_IsNotExists {
            get {
                return ResourceManager.GetString("RoleService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他错误：（{0}） 的本地化字符串。
        /// </summary>
        internal static string RoleService_OtherError {
            get {
                return ResourceManager.GetString("RoleService_OtherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他错误：（{0}） 的本地化字符串。
        /// </summary>
        internal static string UserAuthenticateService_OtherError {
            get {
                return ResourceManager.GetString("UserAuthenticateService_OtherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户（{0}）密码错误。 的本地化字符串。
        /// </summary>
        internal static string UserAuthenticateService_PasswordIsError {
            get {
                return ResourceManager.GetString("UserAuthenticateService_PasswordIsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源数据访问对象为Null。 的本地化字符串。
        /// </summary>
        internal static string UserAuthenticateService_ResourceDataEngineIsNull {
            get {
                return ResourceManager.GetString("UserAuthenticateService_ResourceDataEngineIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源（{0}:{1}）不存在。 的本地化字符串。
        /// </summary>
        internal static string UserAuthenticateService_ResourceIsNotExists {
            get {
                return ResourceManager.GetString("UserAuthenticateService_ResourceIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色资源数据访问对象为Null。 的本地化字符串。
        /// </summary>
        internal static string UserAuthenticateService_RoleOwnResourceDataEngineIsNull {
            get {
                return ResourceManager.GetString("UserAuthenticateService_RoleOwnResourceDataEngineIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户数据访问对象为Null。 的本地化字符串。
        /// </summary>
        internal static string UserAuthenticateService_UserDataEngineIsNull {
            get {
                return ResourceManager.GetString("UserAuthenticateService_UserDataEngineIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户角色数据访问对象为Null。 的本地化字符串。
        /// </summary>
        internal static string UserAuthenticateService_UserInRoleDataEngineIsNull {
            get {
                return ResourceManager.GetString("UserAuthenticateService_UserInRoleDataEngineIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string UserAuthenticateService_UserIsNotExists {
            get {
                return ResourceManager.GetString("UserAuthenticateService_UserIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户资源数据访问对象为Null。 的本地化字符串。
        /// </summary>
        internal static string UserAuthenticateService_UserOwnResourceDataEngineIsNull {
            get {
                return ResourceManager.GetString("UserAuthenticateService_UserOwnResourceDataEngineIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户（{0}）资源（{1}:{2}）不存在。 的本地化字符串。
        /// </summary>
        internal static string UserAuthenticateService_UserResourceIsNotExists {
            get {
                return ResourceManager.GetString("UserAuthenticateService_UserResourceIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户（{0}）已设置角色（{1}）。 的本地化字符串。
        /// </summary>
        internal static string UserInRoleService_IsExists {
            get {
                return ResourceManager.GetString("UserInRoleService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户（{0}）未设置角色（{1}）。 的本地化字符串。
        /// </summary>
        internal static string UserInRoleService_IsNotExists {
            get {
                return ResourceManager.GetString("UserInRoleService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他错误：（{0}） 的本地化字符串。
        /// </summary>
        internal static string UserInRoleService_OtherError {
            get {
                return ResourceManager.GetString("UserInRoleService_OtherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户资源（{0}-{1}:{2}）已存在。 的本地化字符串。
        /// </summary>
        internal static string UserOwnResourceService_IsExists {
            get {
                return ResourceManager.GetString("UserOwnResourceService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户资源（{0}-{1}:{2}）不存在。 的本地化字符串。
        /// </summary>
        internal static string UserOwnResourceService_IsNotExists {
            get {
                return ResourceManager.GetString("UserOwnResourceService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他错误：（{0}） 的本地化字符串。
        /// </summary>
        internal static string UserOwnResourceService_OtherError {
            get {
                return ResourceManager.GetString("UserOwnResourceService_OtherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string UserService_IsExists {
            get {
                return ResourceManager.GetString("UserService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string UserService_IsNotExists {
            get {
                return ResourceManager.GetString("UserService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他错误：（{0}） 的本地化字符串。
        /// </summary>
        internal static string UserService_OtherError {
            get {
                return ResourceManager.GetString("UserService_OtherError", resourceCulture);
            }
        }
    }
}
