//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenter.Client.Mvc.Resources.ZPVM {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceCenter.Client.Mvc.Resources.ZPVM.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 检验时间（止） 的本地化字符串。
        /// </summary>
        public static string CheckDataQueryViewModel_EndCheckTime {
            get {
                return ResourceManager.GetString("CheckDataQueryViewModel_EndCheckTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线别 的本地化字符串。
        /// </summary>
        public static string CheckDataQueryViewModel_LineCode {
            get {
                return ResourceManager.GetString("CheckDataQueryViewModel_LineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验时间（起） 的本地化字符串。
        /// </summary>
        public static string CheckDataQueryViewModel_StartCheckTime {
            get {
                return ResourceManager.GetString("CheckDataQueryViewModel_StartCheckTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除（{0}）? 的本地化字符串。
        /// </summary>
        public static string ChestDetail_ConfirmDelete {
            get {
                return ResourceManager.GetString("ChestDetail_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柜号明细查询 的本地化字符串。
        /// </summary>
        public static string ChestDetail_ManagePageTitle {
            get {
                return ResourceManager.GetString("ChestDetail_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柜号 的本地化字符串。
        /// </summary>
        public static string ChestNo {
            get {
                return ResourceManager.GetString("ChestNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前数量 的本地化字符串。
        /// </summary>
        public static string ChestViewModel_CurrentQuantity {
            get {
                return ResourceManager.GetString("ChestViewModel_CurrentQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 满柜数量 的本地化字符串。
        /// </summary>
        public static string ChestViewModel_FullQuantity {
            get {
                return ResourceManager.GetString("ChestViewModel_FullQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾柜 的本地化字符串。
        /// </summary>
        public static string ChestViewModel_IsLastestPackageInChest {
            get {
                return ResourceManager.GetString("ChestViewModel_IsLastestPackageInChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增衰减系数 的本地化字符串。
        /// </summary>
        public static string Decay_AddTitle {
            get {
                return ResourceManager.GetString("Decay_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除衰减（{0}）系数？ 的本地化字符串。
        /// </summary>
        public static string Decay_ConfirmDelete {
            get {
                return ResourceManager.GetString("Decay_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除系数（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string Decay_Delete_Success {
            get {
                return ResourceManager.GetString("Decay_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 衰减系数信息 的本地化字符串。
        /// </summary>
        public static string Decay_DetailTitle {
            get {
                return ResourceManager.GetString("Decay_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 衰减系数管理 的本地化字符串。
        /// </summary>
        public static string Decay_ManagePageTitle {
            get {
                return ResourceManager.GetString("Decay_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改衰减系数 的本地化字符串。
        /// </summary>
        public static string Decay_ModifyTitle {
            get {
                return ResourceManager.GetString("Decay_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 衰减系数（{0}）保存成功。 的本地化字符串。
        /// </summary>
        public static string Decay_Save_Success {
            get {
                return ResourceManager.GetString("Decay_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改衰减系数（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string Decay_SaveModify_Success {
            get {
                return ResourceManager.GetString("Decay_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        public static string DecayQueryViewModel_Code {
            get {
                return ResourceManager.GetString("DecayQueryViewModel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        public static string DecayViewModel_Code {
            get {
                return ResourceManager.GetString("DecayViewModel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用？ 的本地化字符串。
        /// </summary>
        public static string DecayViewModel_IsUsed {
            get {
                return ResourceManager.GetString("DecayViewModel_IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象 的本地化字符串。
        /// </summary>
        public static string DecayViewModel_Object {
            get {
                return ResourceManager.GetString("DecayViewModel_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string DecayViewModel_Type {
            get {
                return ResourceManager.GetString("DecayViewModel_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        public static string DecayViewModel_Value {
            get {
                return ResourceManager.GetString("DecayViewModel_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增效率档 的本地化字符串。
        /// </summary>
        public static string Efficiency_AddTitle {
            get {
                return ResourceManager.GetString("Efficiency_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除效率档（{0}）？ 的本地化字符串。
        /// </summary>
        public static string Efficiency_ConfirmDelete {
            get {
                return ResourceManager.GetString("Efficiency_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除效率档（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string Efficiency_Delete_Success {
            get {
                return ResourceManager.GetString("Efficiency_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效率档信息 的本地化字符串。
        /// </summary>
        public static string Efficiency_DetailTitle {
            get {
                return ResourceManager.GetString("Efficiency_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效率档管理 的本地化字符串。
        /// </summary>
        public static string Efficiency_ManagePageTitle {
            get {
                return ResourceManager.GetString("Efficiency_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改效率档 的本地化字符串。
        /// </summary>
        public static string Efficiency_ModifyTitle {
            get {
                return ResourceManager.GetString("Efficiency_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效率档（{0}）保存成功。 的本地化字符串。
        /// </summary>
        public static string Efficiency_Save_Success {
            get {
                return ResourceManager.GetString("Efficiency_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改效率档（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string Efficiency_SaveModify_Success {
            get {
                return ResourceManager.GetString("Efficiency_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        public static string EfficiencyQueryViewModel_Code {
            get {
                return ResourceManager.GetString("EfficiencyQueryViewModel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组名 的本地化字符串。
        /// </summary>
        public static string EfficiencyQueryViewModel_Group {
            get {
                return ResourceManager.GetString("EfficiencyQueryViewModel_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        public static string EfficiencyViewModel_Code {
            get {
                return ResourceManager.GetString("EfficiencyViewModel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组名 的本地化字符串。
        /// </summary>
        public static string EfficiencyViewModel_Group {
            get {
                return ResourceManager.GetString("EfficiencyViewModel_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用？ 的本地化字符串。
        /// </summary>
        public static string EfficiencyViewModel_IsUsed {
            get {
                return ResourceManager.GetString("EfficiencyViewModel_IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小值 的本地化字符串。
        /// </summary>
        public static string EfficiencyViewModel_Lower {
            get {
                return ResourceManager.GetString("EfficiencyViewModel_Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string EfficiencyViewModel_Name {
            get {
                return ResourceManager.GetString("EfficiencyViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大值 的本地化字符串。
        /// </summary>
        public static string EfficiencyViewModel_Upper {
            get {
                return ResourceManager.GetString("EfficiencyViewModel_Upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规 的本地化字符串。
        /// </summary>
        public static string EnumPackageListType_Normal {
            get {
                return ResourceManager.GetString("EnumPackageListType_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他 的本地化字符串。
        /// </summary>
        public static string EnumPackageListType_Other {
            get {
                return ResourceManager.GetString("EnumPackageListType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成入柜 的本地化字符串。
        /// </summary>
        public static string FinishPackageInChest {
            get {
                return ResourceManager.GetString("FinishPackageInChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IV测试数据查询 的本地化字符串。
        /// </summary>
        public static string IVTestDataQuery_ManagePageTitle {
            get {
                return ResourceManager.GetString("IVTestDataQuery_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IV数据包装号导出 的本地化字符串。
        /// </summary>
        public static string IVTestDataQueryForPackage_ManagePageTitle {
            get {
                return ResourceManager.GetString("IVTestDataQueryForPackage_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IV数据查询-包装号查询 的本地化字符串。
        /// </summary>
        public static string IVTestDataQueryPackage_ManagePageTitle {
            get {
                return ResourceManager.GetString("IVTestDataQueryPackage_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试时间（止） 的本地化字符串。
        /// </summary>
        public static string IVTestDataQueryViewModel_EndTestTime {
            get {
                return ResourceManager.GetString("IVTestDataQueryViewModel_EndTestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备 的本地化字符串。
        /// </summary>
        public static string IVTestDataQueryViewModel_EquipmentCode {
            get {
                return ResourceManager.GetString("IVTestDataQueryViewModel_EquipmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效值 的本地化字符串。
        /// </summary>
        public static string IVTestDataQueryViewModel_IsDefault {
            get {
                return ResourceManager.GetString("IVTestDataQueryViewModel_IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校准板 的本地化字符串。
        /// </summary>
        public static string IVTestDataQueryViewModel_IsJZ {
            get {
                return ResourceManager.GetString("IVTestDataQueryViewModel_IsJZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        public static string IVTestDataQueryViewModel_IsPrint {
            get {
                return ResourceManager.GetString("IVTestDataQueryViewModel_IsPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线别 的本地化字符串。
        /// </summary>
        public static string IVTestDataQueryViewModel_lineCode {
            get {
                return ResourceManager.GetString("IVTestDataQueryViewModel_lineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试时间（起） 的本地化字符串。
        /// </summary>
        public static string IVTestDataQueryViewModel_StartTestTime {
            get {
                return ResourceManager.GetString("IVTestDataQueryViewModel_StartTestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次号 的本地化字符串。
        /// </summary>
        public static string LotNumber {
            get {
                return ResourceManager.GetString("LotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装号 的本地化字符串。
        /// </summary>
        public static string LotOemPackageQueryViewModel_PackageNo {
            get {
                return ResourceManager.GetString("LotOemPackageQueryViewModel_PackageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功率档 的本地化字符串。
        /// </summary>
        public static string LotOemPackageQueryViewModel_PNOM {
            get {
                return ResourceManager.GetString("LotOemPackageQueryViewModel_PNOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次号 的本地化字符串。
        /// </summary>
        public static string LotOemPackageQueryViewModel_SN {
            get {
                return ResourceManager.GetString("LotOemPackageQueryViewModel_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string LotOemPackageQueryViewModel_Type {
            get {
                return ResourceManager.GetString("LotOemPackageQueryViewModel_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电流档 的本地化字符串。
        /// </summary>
        public static string LotOemPackageViewModel_DL {
            get {
                return ResourceManager.GetString("LotOemPackageViewModel_DL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填充因子 的本地化字符串。
        /// </summary>
        public static string LotOemPackageViewModel_FF {
            get {
                return ResourceManager.GetString("LotOemPackageViewModel_FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作电流 的本地化字符串。
        /// </summary>
        public static string LotOemPackageViewModel_IMP {
            get {
                return ResourceManager.GetString("LotOemPackageViewModel_IMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 短路电流 的本地化字符串。
        /// </summary>
        public static string LotOemPackageViewModel_ISC {
            get {
                return ResourceManager.GetString("LotOemPackageViewModel_ISC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string LotOemPackageViewModel_No {
            get {
                return ResourceManager.GetString("LotOemPackageViewModel_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装号 的本地化字符串。
        /// </summary>
        public static string LotOemPackageViewModel_PackageNo {
            get {
                return ResourceManager.GetString("LotOemPackageViewModel_PackageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实测功率 的本地化字符串。
        /// </summary>
        public static string LotOemPackageViewModel_PMP {
            get {
                return ResourceManager.GetString("LotOemPackageViewModel_PMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功率档 的本地化字符串。
        /// </summary>
        public static string LotOemPackageViewModel_PNOM {
            get {
                return ResourceManager.GetString("LotOemPackageViewModel_PNOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次号 的本地化字符串。
        /// </summary>
        public static string LotOemPackageViewModel_SN {
            get {
                return ResourceManager.GetString("LotOemPackageViewModel_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        public static string LotOemPackageViewModel_Time {
            get {
                return ResourceManager.GetString("LotOemPackageViewModel_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string LotOemPackageViewModel_Type {
            get {
                return ResourceManager.GetString("LotOemPackageViewModel_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作电压 的本地化字符串。
        /// </summary>
        public static string LotOemPackageViewModel_VMP {
            get {
                return ResourceManager.GetString("LotOemPackageViewModel_VMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开路电压 的本地化字符串。
        /// </summary>
        public static string LotOemPackageViewModel_VOC {
            get {
                return ResourceManager.GetString("LotOemPackageViewModel_VOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装数据查询 的本地化字符串。
        /// </summary>
        public static string LotPackageQuery_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotPackageQuery_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装时间（止） 的本地化字符串。
        /// </summary>
        public static string LotPackageQueryViewModel_EndCreateTime {
            get {
                return ResourceManager.GetString("LotPackageQueryViewModel_EndCreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string LotPackageQueryViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("LotPackageQueryViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装时间（起） 的本地化字符串。
        /// </summary>
        public static string LotPackageQueryViewModel_StartCreateTime {
            get {
                return ResourceManager.GetString("LotPackageQueryViewModel_StartCreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装数据导出XML 的本地化字符串。
        /// </summary>
        public static string LotPackageSEModules_ManagePageTitle {
            get {
                return ResourceManager.GetString("LotPackageSEModules_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料替换规则保存成功！ 的本地化字符串。
        /// </summary>
        public static string MaterialReplace_Save_Success {
            get {
                return ResourceManager.GetString("MaterialReplace_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铭牌打印 的本地化字符串。
        /// </summary>
        public static string NameplatePrint_ManagePageTitle {
            get {
                return ResourceManager.GetString("NameplatePrint_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复打印？ 的本地化字符串。
        /// </summary>
        public static string NameplatePrintViewModel_IsRepeatPrint {
            get {
                return ResourceManager.GetString("NameplatePrintViewModel_IsRepeatPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印机名称 的本地化字符串。
        /// </summary>
        public static string NameplatePrintViewModel_PrinterName {
            get {
                return ResourceManager.GetString("NameplatePrintViewModel_PrinterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铭牌代码 的本地化字符串。
        /// </summary>
        public static string NameplatePrintViewModel_PrintLabelCode {
            get {
                return ResourceManager.GetString("NameplatePrintViewModel_PrintLabelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印数量 的本地化字符串。
        /// </summary>
        public static string NameplatePrintViewModel_PrintQty {
            get {
                return ResourceManager.GetString("NameplatePrintViewModel_PrintQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入柜 的本地化字符串。
        /// </summary>
        public static string PackageInChest {
            get {
                return ResourceManager.GetString("PackageInChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入柜作业 的本地化字符串。
        /// </summary>
        public static string PackageInChest_ManagePageTitle {
            get {
                return ResourceManager.GetString("PackageInChest_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装号 的本地化字符串。
        /// </summary>
        public static string PackageNo {
            get {
                return ResourceManager.GetString("PackageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次号？ 的本地化字符串。
        /// </summary>
        public static string PackingListPrintQueryViewModel_IsLotNumber {
            get {
                return ResourceManager.GetString("PackingListPrintQueryViewModel_IsLotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装清单类型 的本地化字符串。
        /// </summary>
        public static string PackingListPrintQueryViewModel_PackageListType {
            get {
                return ResourceManager.GetString("PackingListPrintQueryViewModel_PackageListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装号 的本地化字符串。
        /// </summary>
        public static string PackingListPrintQueryViewModel_PackageNo {
            get {
                return ResourceManager.GetString("PackingListPrintQueryViewModel_PackageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增分档 的本地化字符串。
        /// </summary>
        public static string Powerset_AddTitle {
            get {
                return ResourceManager.GetString("Powerset_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除分档（{0}）？ 的本地化字符串。
        /// </summary>
        public static string Powerset_ConfirmDelete {
            get {
                return ResourceManager.GetString("Powerset_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除分档（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string Powerset_Delete_Success {
            get {
                return ResourceManager.GetString("Powerset_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分档信息 的本地化字符串。
        /// </summary>
        public static string Powerset_DetailTitle {
            get {
                return ResourceManager.GetString("Powerset_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分档管理 的本地化字符串。
        /// </summary>
        public static string Powerset_ManagePageTitle {
            get {
                return ResourceManager.GetString("Powerset_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改分档 的本地化字符串。
        /// </summary>
        public static string Powerset_ModifyTitle {
            get {
                return ResourceManager.GetString("Powerset_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分档（{0}）保存成功。 的本地化字符串。
        /// </summary>
        public static string Powerset_Save_Success {
            get {
                return ResourceManager.GetString("Powerset_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改分档（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string Powerset_SaveModify_Success {
            get {
                return ResourceManager.GetString("Powerset_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增子分档 的本地化字符串。
        /// </summary>
        public static string PowersetDetail_AddTitle {
            get {
                return ResourceManager.GetString("PowersetDetail_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除子分档（{0}）？ 的本地化字符串。
        /// </summary>
        public static string PowersetDetail_ConfirmDelete {
            get {
                return ResourceManager.GetString("PowersetDetail_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除子分档（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string PowersetDetail_Delete_Success {
            get {
                return ResourceManager.GetString("PowersetDetail_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子分档信息 的本地化字符串。
        /// </summary>
        public static string PowersetDetail_DetailTitle {
            get {
                return ResourceManager.GetString("PowersetDetail_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分档（{0}）子分档管理 的本地化字符串。
        /// </summary>
        public static string PowersetDetail_ManagePageTitle {
            get {
                return ResourceManager.GetString("PowersetDetail_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改子分档 的本地化字符串。
        /// </summary>
        public static string PowersetDetail_ModifyTitle {
            get {
                return ResourceManager.GetString("PowersetDetail_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子分档（{0}）保存成功。 的本地化字符串。
        /// </summary>
        public static string PowersetDetail_Save_Success {
            get {
                return ResourceManager.GetString("PowersetDetail_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改子分档（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string PowersetDetail_SaveModify_Success {
            get {
                return ResourceManager.GetString("PowersetDetail_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分档代码 的本地化字符串。
        /// </summary>
        public static string PowersetDetailQueryViewModel_Code {
            get {
                return ResourceManager.GetString("PowersetDetailQueryViewModel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目号 的本地化字符串。
        /// </summary>
        public static string PowersetDetailQueryViewModel_ItemNo {
            get {
                return ResourceManager.GetString("PowersetDetailQueryViewModel_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子分档代码 的本地化字符串。
        /// </summary>
        public static string PowersetDetailQueryViewModel_SubCode {
            get {
                return ResourceManager.GetString("PowersetDetailQueryViewModel_SubCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分档代码 的本地化字符串。
        /// </summary>
        public static string PowersetDetailViewModel_Code {
            get {
                return ResourceManager.GetString("PowersetDetailViewModel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除图片？ 的本地化字符串。
        /// </summary>
        public static string PowersetDetailViewModel_IsDeletePicture {
            get {
                return ResourceManager.GetString("PowersetDetailViewModel_IsDeletePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用？ 的本地化字符串。
        /// </summary>
        public static string PowersetDetailViewModel_IsUsed {
            get {
                return ResourceManager.GetString("PowersetDetailViewModel_IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分档项目号 的本地化字符串。
        /// </summary>
        public static string PowersetDetailViewModel_ItemNo {
            get {
                return ResourceManager.GetString("PowersetDetailViewModel_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大值 的本地化字符串。
        /// </summary>
        public static string PowersetDetailViewModel_MaxValue {
            get {
                return ResourceManager.GetString("PowersetDetailViewModel_MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小值 的本地化字符串。
        /// </summary>
        public static string PowersetDetailViewModel_MinValue {
            get {
                return ResourceManager.GetString("PowersetDetailViewModel_MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        public static string PowersetDetailViewModel_Picture {
            get {
                return ResourceManager.GetString("PowersetDetailViewModel_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子分档代码 的本地化字符串。
        /// </summary>
        public static string PowersetDetailViewModel_SubCode {
            get {
                return ResourceManager.GetString("PowersetDetailViewModel_SubCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子分档名称 的本地化字符串。
        /// </summary>
        public static string PowersetDetailViewModel_SubName {
            get {
                return ResourceManager.GetString("PowersetDetailViewModel_SubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分档代码 的本地化字符串。
        /// </summary>
        public static string PowersetQueryViewModel_Code {
            get {
                return ResourceManager.GetString("PowersetQueryViewModel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分档名称 的本地化字符串。
        /// </summary>
        public static string PowersetQueryViewModel_Name {
            get {
                return ResourceManager.GetString("PowersetQueryViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分档方式 的本地化字符串。
        /// </summary>
        public static string PowersetQueryViewModel_PowerDifference {
            get {
                return ResourceManager.GetString("PowersetQueryViewModel_PowerDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 档位名称 的本地化字符串。
        /// </summary>
        public static string PowersetQueryViewModel_PowerName {
            get {
                return ResourceManager.GetString("PowersetQueryViewModel_PowerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ArticleNo 的本地化字符串。
        /// </summary>
        public static string PowersetViewModel_ArticleNo {
            get {
                return ResourceManager.GetString("PowersetViewModel_ArticleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分档代码 的本地化字符串。
        /// </summary>
        public static string PowersetViewModel_Code {
            get {
                return ResourceManager.GetString("PowersetViewModel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用？ 的本地化字符串。
        /// </summary>
        public static string PowersetViewModel_IsUsed {
            get {
                return ResourceManager.GetString("PowersetViewModel_IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分档项目号 的本地化字符串。
        /// </summary>
        public static string PowersetViewModel_ItemNo {
            get {
                return ResourceManager.GetString("PowersetViewModel_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大值 的本地化字符串。
        /// </summary>
        public static string PowersetViewModel_MaxValue {
            get {
                return ResourceManager.GetString("PowersetViewModel_MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小值 的本地化字符串。
        /// </summary>
        public static string PowersetViewModel_MinValue {
            get {
                return ResourceManager.GetString("PowersetViewModel_MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 混颜色？ 的本地化字符串。
        /// </summary>
        public static string PowersetViewModel_MixColor {
            get {
                return ResourceManager.GetString("PowersetViewModel_MixColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分档名称 的本地化字符串。
        /// </summary>
        public static string PowersetViewModel_Name {
            get {
                return ResourceManager.GetString("PowersetViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分档方式 的本地化字符串。
        /// </summary>
        public static string PowersetViewModel_PowerDifference {
            get {
                return ResourceManager.GetString("PowersetViewModel_PowerDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 档位名称 的本地化字符串。
        /// </summary>
        public static string PowersetViewModel_PowerName {
            get {
                return ResourceManager.GetString("PowersetViewModel_PowerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准填充因子 的本地化字符串。
        /// </summary>
        public static string PowersetViewModel_StandardFuse {
            get {
                return ResourceManager.GetString("PowersetViewModel_StandardFuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准最大电流 的本地化字符串。
        /// </summary>
        public static string PowersetViewModel_StandardIPM {
            get {
                return ResourceManager.GetString("PowersetViewModel_StandardIPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准电流 的本地化字符串。
        /// </summary>
        public static string PowersetViewModel_StandardIsc {
            get {
                return ResourceManager.GetString("PowersetViewModel_StandardIsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准功率 的本地化字符串。
        /// </summary>
        public static string PowersetViewModel_StandardPower {
            get {
                return ResourceManager.GetString("PowersetViewModel_StandardPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准电压 的本地化字符串。
        /// </summary>
        public static string PowersetViewModel_StandardVoc {
            get {
                return ResourceManager.GetString("PowersetViewModel_StandardVoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准最大电压 的本地化字符串。
        /// </summary>
        public static string PowersetViewModel_StandardVPM {
            get {
                return ResourceManager.GetString("PowersetViewModel_StandardVPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子分档方法 的本地化字符串。
        /// </summary>
        public static string PowersetViewModel_SubWay {
            get {
                return ResourceManager.GetString("PowersetViewModel_SubWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除产品分档设置（{0}）？ 的本地化字符串。
        /// </summary>
        public static string ProductControlObject_ConfirmDelete {
            get {
                return ResourceManager.GetString("ProductControlObject_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除产品规则（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string ProductControlObject_Delete_Success {
            get {
                return ResourceManager.GetString("ProductControlObject_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存产品规则( {0} )成功。 的本地化字符串。
        /// </summary>
        public static string ProductControlObject_Save_Success {
            get {
                return ResourceManager.GetString("ProductControlObject_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改产品规则（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string ProductControlObject_SaveModify_Success {
            get {
                return ResourceManager.GetString("ProductControlObject_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电池片效率 的本地化字符串。
        /// </summary>
        public static string ProductControlObjectQueryViewModel_CellEff {
            get {
                return ResourceManager.GetString("ProductControlObjectQueryViewModel_CellEff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品代码 的本地化字符串。
        /// </summary>
        public static string ProductControlObjectQueryViewModel_ProductCode {
            get {
                return ResourceManager.GetString("ProductControlObjectQueryViewModel_ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商代码 的本地化字符串。
        /// </summary>
        public static string ProductControlObjectQueryViewModel_SupplierCode {
            get {
                return ResourceManager.GetString("ProductControlObjectQueryViewModel_SupplierCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电池片效率 的本地化字符串。
        /// </summary>
        public static string ProductControlObjectViewModel_CellEff {
            get {
                return ResourceManager.GetString("ProductControlObjectViewModel_CellEff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否可用 的本地化字符串。
        /// </summary>
        public static string ProductControlObjectViewModel_IsUsed {
            get {
                return ResourceManager.GetString("ProductControlObjectViewModel_IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制对象 的本地化字符串。
        /// </summary>
        public static string ProductControlObjectViewModel_Object {
            get {
                return ResourceManager.GetString("ProductControlObjectViewModel_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品代码 的本地化字符串。
        /// </summary>
        public static string ProductControlObjectViewModel_ProductCode {
            get {
                return ResourceManager.GetString("ProductControlObjectViewModel_ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称 的本地化字符串。
        /// </summary>
        public static string ProductControlObjectViewModel_ProductName {
            get {
                return ResourceManager.GetString("ProductControlObjectViewModel_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商代码 的本地化字符串。
        /// </summary>
        public static string ProductControlObjectViewModel_SupplierCode {
            get {
                return ResourceManager.GetString("ProductControlObjectViewModel_SupplierCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商名称 的本地化字符串。
        /// </summary>
        public static string ProductControlObjectViewModel_SupplierName {
            get {
                return ResourceManager.GetString("ProductControlObjectViewModel_SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制类型 的本地化字符串。
        /// </summary>
        public static string ProductControlObjectViewModel_Type {
            get {
                return ResourceManager.GetString("ProductControlObjectViewModel_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制值 的本地化字符串。
        /// </summary>
        public static string ProductControlObjectViewModel_Value {
            get {
                return ResourceManager.GetString("ProductControlObjectViewModel_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增规则 的本地化字符串。
        /// </summary>
        public static string Rule_AddTitle {
            get {
                return ResourceManager.GetString("Rule_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除规则（{0}）？ 的本地化字符串。
        /// </summary>
        public static string Rule_ConfirmDelete {
            get {
                return ResourceManager.GetString("Rule_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除规则（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string Rule_Delete_Success {
            get {
                return ResourceManager.GetString("Rule_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则信息 的本地化字符串。
        /// </summary>
        public static string Rule_DetailTitle {
            get {
                return ResourceManager.GetString("Rule_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则管理 的本地化字符串。
        /// </summary>
        public static string Rule_ManagePageTitle {
            get {
                return ResourceManager.GetString("Rule_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改规则 的本地化字符串。
        /// </summary>
        public static string Rule_ModifyTitle {
            get {
                return ResourceManager.GetString("Rule_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则（{0}）保存成功。 的本地化字符串。
        /// </summary>
        public static string Rule_Save_Success {
            get {
                return ResourceManager.GetString("Rule_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改规则（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string Rule_SaveModify_Success {
            get {
                return ResourceManager.GetString("Rule_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增控制参数 的本地化字符串。
        /// </summary>
        public static string RuleControlObject_AddTitle {
            get {
                return ResourceManager.GetString("RuleControlObject_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除控制参数（{0}）？ 的本地化字符串。
        /// </summary>
        public static string RuleControlObject_ConfirmDelete {
            get {
                return ResourceManager.GetString("RuleControlObject_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除控制参数（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string RuleControlObject_Delete_Success {
            get {
                return ResourceManager.GetString("RuleControlObject_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制参数信息 的本地化字符串。
        /// </summary>
        public static string RuleControlObject_DetailTitle {
            get {
                return ResourceManager.GetString("RuleControlObject_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则（{0}）控制参数管理 的本地化字符串。
        /// </summary>
        public static string RuleControlObject_ManagePageTitle {
            get {
                return ResourceManager.GetString("RuleControlObject_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改控制参数 的本地化字符串。
        /// </summary>
        public static string RuleControlObject_ModifyTitle {
            get {
                return ResourceManager.GetString("RuleControlObject_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制参数（{0}）保存成功。 的本地化字符串。
        /// </summary>
        public static string RuleControlObject_Save_Success {
            get {
                return ResourceManager.GetString("RuleControlObject_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改控制参数（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string RuleControlObject_SaveModify_Success {
            get {
                return ResourceManager.GetString("RuleControlObject_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则代码 的本地化字符串。
        /// </summary>
        public static string RuleControlObjectQueryViewModel_Code {
            get {
                return ResourceManager.GetString("RuleControlObjectQueryViewModel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则代码 的本地化字符串。
        /// </summary>
        public static string RuleControlObjectViewModel_Code {
            get {
                return ResourceManager.GetString("RuleControlObjectViewModel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用？ 的本地化字符串。
        /// </summary>
        public static string RuleControlObjectViewModel_IsUsed {
            get {
                return ResourceManager.GetString("RuleControlObjectViewModel_IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制参数 的本地化字符串。
        /// </summary>
        public static string RuleControlObjectViewModel_Object {
            get {
                return ResourceManager.GetString("RuleControlObjectViewModel_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制类型 的本地化字符串。
        /// </summary>
        public static string RuleControlObjectViewModel_Type {
            get {
                return ResourceManager.GetString("RuleControlObjectViewModel_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制值 的本地化字符串。
        /// </summary>
        public static string RuleControlObjectViewModel_Value {
            get {
                return ResourceManager.GetString("RuleControlObjectViewModel_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增衰减 的本地化字符串。
        /// </summary>
        public static string RuleDecay_AddTitle {
            get {
                return ResourceManager.GetString("RuleDecay_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除衰减（{0}）？ 的本地化字符串。
        /// </summary>
        public static string RuleDecay_ConfirmDelete {
            get {
                return ResourceManager.GetString("RuleDecay_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除衰减（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string RuleDecay_Delete_Success {
            get {
                return ResourceManager.GetString("RuleDecay_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 衰减信息 的本地化字符串。
        /// </summary>
        public static string RuleDecay_DetailTitle {
            get {
                return ResourceManager.GetString("RuleDecay_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则（{0}）衰减管理 的本地化字符串。
        /// </summary>
        public static string RuleDecay_ManagePageTitle {
            get {
                return ResourceManager.GetString("RuleDecay_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改衰减 的本地化字符串。
        /// </summary>
        public static string RuleDecay_ModifyTitle {
            get {
                return ResourceManager.GetString("RuleDecay_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 衰减（{0}）保存成功。 的本地化字符串。
        /// </summary>
        public static string RuleDecay_Save_Success {
            get {
                return ResourceManager.GetString("RuleDecay_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改衰减（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string RuleDecay_SaveModify_Success {
            get {
                return ResourceManager.GetString("RuleDecay_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则代码 的本地化字符串。
        /// </summary>
        public static string RuleDecayQueryViewModel_Code {
            get {
                return ResourceManager.GetString("RuleDecayQueryViewModel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则代码 的本地化字符串。
        /// </summary>
        public static string RuleDecayViewModel_Code {
            get {
                return ResourceManager.GetString("RuleDecayViewModel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 衰减代码 的本地化字符串。
        /// </summary>
        public static string RuleDecayViewModel_DecayCode {
            get {
                return ResourceManager.GetString("RuleDecayViewModel_DecayCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用？ 的本地化字符串。
        /// </summary>
        public static string RuleDecayViewModel_IsUsed {
            get {
                return ResourceManager.GetString("RuleDecayViewModel_IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功率下限 的本地化字符串。
        /// </summary>
        public static string RuleDecayViewModel_MaxPower {
            get {
                return ResourceManager.GetString("RuleDecayViewModel_MaxPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功率上限 的本地化字符串。
        /// </summary>
        public static string RuleDecayViewModel_MinPower {
            get {
                return ResourceManager.GetString("RuleDecayViewModel_MinPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增等级 的本地化字符串。
        /// </summary>
        public static string RuleGrade_AddTitle {
            get {
                return ResourceManager.GetString("RuleGrade_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除等级（{0}）？ 的本地化字符串。
        /// </summary>
        public static string RuleGrade_ConfirmDelete {
            get {
                return ResourceManager.GetString("RuleGrade_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除等级（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string RuleGrade_Delete_Success {
            get {
                return ResourceManager.GetString("RuleGrade_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等级信息 的本地化字符串。
        /// </summary>
        public static string RuleGrade_DetailTitle {
            get {
                return ResourceManager.GetString("RuleGrade_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则（{0}）等级设置 的本地化字符串。
        /// </summary>
        public static string RuleGrade_ManagePageTitle {
            get {
                return ResourceManager.GetString("RuleGrade_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改等级 的本地化字符串。
        /// </summary>
        public static string RuleGrade_ModifyTitle {
            get {
                return ResourceManager.GetString("RuleGrade_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等级（{0}）保存成功。 的本地化字符串。
        /// </summary>
        public static string RuleGrade_Save_Success {
            get {
                return ResourceManager.GetString("RuleGrade_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改等级（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string RuleGrade_SaveModify_Success {
            get {
                return ResourceManager.GetString("RuleGrade_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则代码 的本地化字符串。
        /// </summary>
        public static string RuleGradeQueryViewModel_Code {
            get {
                return ResourceManager.GetString("RuleGradeQueryViewModel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则代码 的本地化字符串。
        /// </summary>
        public static string RuleGradeViewModel_Code {
            get {
                return ResourceManager.GetString("RuleGradeViewModel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等级 的本地化字符串。
        /// </summary>
        public static string RuleGradeViewModel_Grade {
            get {
                return ResourceManager.GetString("RuleGradeViewModel_Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用？ 的本地化字符串。
        /// </summary>
        public static string RuleGradeViewModel_IsUsed {
            get {
                return ResourceManager.GetString("RuleGradeViewModel_IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目号 的本地化字符串。
        /// </summary>
        public static string RuleGradeViewModel_ItemNo {
            get {
                return ResourceManager.GetString("RuleGradeViewModel_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许混花 的本地化字符串。
        /// </summary>
        public static string RuleGradeViewModel_MixColor {
            get {
                return ResourceManager.GetString("RuleGradeViewModel_MixColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许混档 的本地化字符串。
        /// </summary>
        public static string RuleGradeViewModel_MixPowerset {
            get {
                return ResourceManager.GetString("RuleGradeViewModel_MixPowerset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许混子分档 的本地化字符串。
        /// </summary>
        public static string RuleGradeViewModel_MixSubPowerset {
            get {
                return ResourceManager.GetString("RuleGradeViewModel_MixSubPowerset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装组 的本地化字符串。
        /// </summary>
        public static string RuleGradeViewModel_PackageGroup {
            get {
                return ResourceManager.GetString("RuleGradeViewModel_PackageGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增标签 的本地化字符串。
        /// </summary>
        public static string RulePrintSet_AddTitle {
            get {
                return ResourceManager.GetString("RulePrintSet_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除标签（{0}）？ 的本地化字符串。
        /// </summary>
        public static string RulePrintSet_ConfirmDelete {
            get {
                return ResourceManager.GetString("RulePrintSet_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除标签（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string RulePrintSet_Delete_Success {
            get {
                return ResourceManager.GetString("RulePrintSet_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签信息 的本地化字符串。
        /// </summary>
        public static string RulePrintSet_DetailTitle {
            get {
                return ResourceManager.GetString("RulePrintSet_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则（{0}）标签管理 的本地化字符串。
        /// </summary>
        public static string RulePrintSet_ManagePageTitle {
            get {
                return ResourceManager.GetString("RulePrintSet_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改标签 的本地化字符串。
        /// </summary>
        public static string RulePrintSet_ModifyTitle {
            get {
                return ResourceManager.GetString("RulePrintSet_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签（{0}）保存成功。 的本地化字符串。
        /// </summary>
        public static string RulePrintSet_Save_Success {
            get {
                return ResourceManager.GetString("RulePrintSet_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改标签（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string RulePrintSet_SaveModify_Success {
            get {
                return ResourceManager.GetString("RulePrintSet_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则代码 的本地化字符串。
        /// </summary>
        public static string RulePrintSetQueryViewModel_Code {
            get {
                return ResourceManager.GetString("RulePrintSetQueryViewModel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则代码 的本地化字符串。
        /// </summary>
        public static string RulePrintSetViewModel_Code {
            get {
                return ResourceManager.GetString("RulePrintSetViewModel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用？ 的本地化字符串。
        /// </summary>
        public static string RulePrintSetViewModel_IsUsed {
            get {
                return ResourceManager.GetString("RulePrintSetViewModel_IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目号 的本地化字符串。
        /// </summary>
        public static string RulePrintSetViewModel_ItemNo {
            get {
                return ResourceManager.GetString("RulePrintSetViewModel_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签代码 的本地化字符串。
        /// </summary>
        public static string RulePrintSetViewModel_LabelCode {
            get {
                return ResourceManager.GetString("RulePrintSetViewModel_LabelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string RulePrintSetViewModel_Qty {
            get {
                return ResourceManager.GetString("RulePrintSetViewModel_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则代码 的本地化字符串。
        /// </summary>
        public static string RuleQueryViewModel_Code {
            get {
                return ResourceManager.GetString("RuleQueryViewModel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则名称 的本地化字符串。
        /// </summary>
        public static string RuleQueryViewModel_Name {
            get {
                return ResourceManager.GetString("RuleQueryViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校准周期（分钟） 的本地化字符串。
        /// </summary>
        public static string RuleViewModel_CalibrationCycle {
            get {
                return ResourceManager.GetString("RuleViewModel_CalibrationCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校准板类型 的本地化字符串。
        /// </summary>
        public static string RuleViewModel_CalibrationType {
            get {
                return ResourceManager.GetString("RuleViewModel_CalibrationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则代码 的本地化字符串。
        /// </summary>
        public static string RuleViewModel_Code {
            get {
                return ResourceManager.GetString("RuleViewModel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固化周期（分钟） 的本地化字符串。
        /// </summary>
        public static string RuleViewModel_FixCycle {
            get {
                return ResourceManager.GetString("RuleViewModel_FixCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 满包数量 的本地化字符串。
        /// </summary>
        public static string RuleViewModel_FullPackageQty {
            get {
                return ResourceManager.GetString("RuleViewModel_FullPackageQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用？ 的本地化字符串。
        /// </summary>
        public static string RuleViewModel_IsUsed {
            get {
                return ResourceManager.GetString("RuleViewModel_IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大功率 的本地化字符串。
        /// </summary>
        public static string RuleViewModel_MaxPower {
            get {
                return ResourceManager.GetString("RuleViewModel_MaxPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小功率 的本地化字符串。
        /// </summary>
        public static string RuleViewModel_MinPower {
            get {
                return ResourceManager.GetString("RuleViewModel_MinPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则名称 的本地化字符串。
        /// </summary>
        public static string RuleViewModel_Name {
            get {
                return ResourceManager.GetString("RuleViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功率精度 的本地化字符串。
        /// </summary>
        public static string RuleViewModel_PowerDegree {
            get {
                return ResourceManager.GetString("RuleViewModel_PowerDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分档代码 的本地化字符串。
        /// </summary>
        public static string RuleViewModel_PowersetCode {
            get {
                return ResourceManager.GetString("RuleViewModel_PowersetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商转换生产厂商规则保存成功！ 的本地化字符串。
        /// </summary>
        public static string SupplierToManufacturer_Save_Success {
            get {
                return ResourceManager.GetString("SupplierToManufacturer_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安规数据查询 的本地化字符串。
        /// </summary>
        public static string VIRTestDataQuery_ManagePageTitle {
            get {
                return ResourceManager.GetString("VIRTestDataQuery_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间 的本地化字符串。
        /// </summary>
        public static string VIRTestDataQueryViewModel_EndTestTime {
            get {
                return ResourceManager.GetString("VIRTestDataQueryViewModel_EndTestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备代码 的本地化字符串。
        /// </summary>
        public static string VIRTestDataQueryViewModel_EquipmentCode {
            get {
                return ResourceManager.GetString("VIRTestDataQueryViewModel_EquipmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次号 的本地化字符串。
        /// </summary>
        public static string VIRTestDataQueryViewModel_LotNumber {
            get {
                return ResourceManager.GetString("VIRTestDataQueryViewModel_LotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        public static string VIRTestDataQueryViewModel_StartTestTime {
            get {
                return ResourceManager.GetString("VIRTestDataQueryViewModel_StartTestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增工单控制参数 的本地化字符串。
        /// </summary>
        public static string WorkOrderControlObject_AddTitle {
            get {
                return ResourceManager.GetString("WorkOrderControlObject_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除工单控制参数（{0}）？ 的本地化字符串。
        /// </summary>
        public static string WorkOrderControlObject_ConfirmDelete {
            get {
                return ResourceManager.GetString("WorkOrderControlObject_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除工单控制参数（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderControlObject_Delete_Success {
            get {
                return ResourceManager.GetString("WorkOrderControlObject_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单控制参数信息 的本地化字符串。
        /// </summary>
        public static string WorkOrderControlObject_DetailTitle {
            get {
                return ResourceManager.GetString("WorkOrderControlObject_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单（{0}）控制参数管理 的本地化字符串。
        /// </summary>
        public static string WorkOrderControlObject_ManagePageTitle {
            get {
                return ResourceManager.GetString("WorkOrderControlObject_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单控制参数 的本地化字符串。
        /// </summary>
        public static string WorkOrderControlObject_ModifyTitle {
            get {
                return ResourceManager.GetString("WorkOrderControlObject_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单控制参数（{0}）保存成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderControlObject_Save_Success {
            get {
                return ResourceManager.GetString("WorkOrderControlObject_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单控制参数（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderControlObject_SaveModify_Success {
            get {
                return ResourceManager.GetString("WorkOrderControlObject_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品号 的本地化字符串。
        /// </summary>
        public static string WorkOrderControlObjectQueryViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("WorkOrderControlObjectQueryViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string WorkOrderControlObjectQueryViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderControlObjectQueryViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用？ 的本地化字符串。
        /// </summary>
        public static string WorkOrderControlObjectViewModel_IsUsed {
            get {
                return ResourceManager.GetString("WorkOrderControlObjectViewModel_IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品号 的本地化字符串。
        /// </summary>
        public static string WorkOrderControlObjectViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("WorkOrderControlObjectViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制对象 的本地化字符串。
        /// </summary>
        public static string WorkOrderControlObjectViewModel_Object {
            get {
                return ResourceManager.GetString("WorkOrderControlObjectViewModel_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string WorkOrderControlObjectViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderControlObjectViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制类型 的本地化字符串。
        /// </summary>
        public static string WorkOrderControlObjectViewModel_Type {
            get {
                return ResourceManager.GetString("WorkOrderControlObjectViewModel_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制值 的本地化字符串。
        /// </summary>
        public static string WorkOrderControlObjectViewModel_Value {
            get {
                return ResourceManager.GetString("WorkOrderControlObjectViewModel_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增工单衰减设置 的本地化字符串。
        /// </summary>
        public static string WorkOrderDecay_AddTitle {
            get {
                return ResourceManager.GetString("WorkOrderDecay_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除工单衰减设置（{0}）？ 的本地化字符串。
        /// </summary>
        public static string WorkOrderDecay_ConfirmDelete {
            get {
                return ResourceManager.GetString("WorkOrderDecay_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除工单衰减设置（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderDecay_Delete_Success {
            get {
                return ResourceManager.GetString("WorkOrderDecay_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单衰减设置信息 的本地化字符串。
        /// </summary>
        public static string WorkOrderDecay_DetailTitle {
            get {
                return ResourceManager.GetString("WorkOrderDecay_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单（{0}）衰减设置管理 的本地化字符串。
        /// </summary>
        public static string WorkOrderDecay_ManagePageTitle {
            get {
                return ResourceManager.GetString("WorkOrderDecay_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单衰减设置 的本地化字符串。
        /// </summary>
        public static string WorkOrderDecay_ModifyTitle {
            get {
                return ResourceManager.GetString("WorkOrderDecay_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单衰减设置（{0}）保存成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderDecay_Save_Success {
            get {
                return ResourceManager.GetString("WorkOrderDecay_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单衰减设置（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderDecay_SaveModify_Success {
            get {
                return ResourceManager.GetString("WorkOrderDecay_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增工单等级设置 的本地化字符串。
        /// </summary>
        public static string WorkOrderGrade_AddTitle {
            get {
                return ResourceManager.GetString("WorkOrderGrade_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除工单等级设置（{0}）？ 的本地化字符串。
        /// </summary>
        public static string WorkOrderGrade_ConfirmDelete {
            get {
                return ResourceManager.GetString("WorkOrderGrade_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除工单等级设置（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderGrade_Delete_Success {
            get {
                return ResourceManager.GetString("WorkOrderGrade_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单等级设置信息 的本地化字符串。
        /// </summary>
        public static string WorkOrderGrade_DetailTitle {
            get {
                return ResourceManager.GetString("WorkOrderGrade_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单（{0}）等级设置管理 的本地化字符串。
        /// </summary>
        public static string WorkOrderGrade_ManagePageTitle {
            get {
                return ResourceManager.GetString("WorkOrderGrade_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单等级设置 的本地化字符串。
        /// </summary>
        public static string WorkOrderGrade_ModifyTitle {
            get {
                return ResourceManager.GetString("WorkOrderGrade_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单等级设置（{0}）保存成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderGrade_Save_Success {
            get {
                return ResourceManager.GetString("WorkOrderGrade_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单等级设置（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderGrade_SaveModify_Success {
            get {
                return ResourceManager.GetString("WorkOrderGrade_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增工单分档规则 的本地化字符串。
        /// </summary>
        public static string WorkOrderPowerset_AddTitle {
            get {
                return ResourceManager.GetString("WorkOrderPowerset_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除工单分档规则（{0}）？ 的本地化字符串。
        /// </summary>
        public static string WorkOrderPowerset_ConfirmDelete {
            get {
                return ResourceManager.GetString("WorkOrderPowerset_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除工单分档规则（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderPowerset_Delete_Success {
            get {
                return ResourceManager.GetString("WorkOrderPowerset_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单分档规则信息 的本地化字符串。
        /// </summary>
        public static string WorkOrderPowerset_DetailTitle {
            get {
                return ResourceManager.GetString("WorkOrderPowerset_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单（{0}）分档规则管理 的本地化字符串。
        /// </summary>
        public static string WorkOrderPowerset_ManagePageTitle {
            get {
                return ResourceManager.GetString("WorkOrderPowerset_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单分档规则 的本地化字符串。
        /// </summary>
        public static string WorkOrderPowerset_ModifyTitle {
            get {
                return ResourceManager.GetString("WorkOrderPowerset_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单分档规则（{0}）保存成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderPowerset_Save_Success {
            get {
                return ResourceManager.GetString("WorkOrderPowerset_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单分档规则（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderPowerset_SaveModify_Success {
            get {
                return ResourceManager.GetString("WorkOrderPowerset_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增工单子分档设置 的本地化字符串。
        /// </summary>
        public static string WorkOrderPowersetDetail_AddTitle {
            get {
                return ResourceManager.GetString("WorkOrderPowersetDetail_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除工单子分档设置（{0}）？ 的本地化字符串。
        /// </summary>
        public static string WorkOrderPowersetDetail_ConfirmDelete {
            get {
                return ResourceManager.GetString("WorkOrderPowersetDetail_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除工单子分档设置（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderPowersetDetail_Delete_Success {
            get {
                return ResourceManager.GetString("WorkOrderPowersetDetail_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单子分档设置信息 的本地化字符串。
        /// </summary>
        public static string WorkOrderPowersetDetail_DetailTitle {
            get {
                return ResourceManager.GetString("WorkOrderPowersetDetail_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单（{0}）子分档设置管理 的本地化字符串。
        /// </summary>
        public static string WorkOrderPowersetDetail_ManagePageTitle {
            get {
                return ResourceManager.GetString("WorkOrderPowersetDetail_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单子分档设置 的本地化字符串。
        /// </summary>
        public static string WorkOrderPowersetDetail_ModifyTitle {
            get {
                return ResourceManager.GetString("WorkOrderPowersetDetail_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单子分档设置（{0}）保存成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderPowersetDetail_Save_Success {
            get {
                return ResourceManager.GetString("WorkOrderPowersetDetail_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单子分档设置（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderPowersetDetail_SaveModify_Success {
            get {
                return ResourceManager.GetString("WorkOrderPowersetDetail_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增工单标签设置 的本地化字符串。
        /// </summary>
        public static string WorkOrderPrintSet_AddTitle {
            get {
                return ResourceManager.GetString("WorkOrderPrintSet_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除工单标签设置（{0}）？ 的本地化字符串。
        /// </summary>
        public static string WorkOrderPrintSet_ConfirmDelete {
            get {
                return ResourceManager.GetString("WorkOrderPrintSet_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除工单标签设置（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderPrintSet_Delete_Success {
            get {
                return ResourceManager.GetString("WorkOrderPrintSet_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单标签设置信息 的本地化字符串。
        /// </summary>
        public static string WorkOrderPrintSet_DetailTitle {
            get {
                return ResourceManager.GetString("WorkOrderPrintSet_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单（{0}）标签设置管理 的本地化字符串。
        /// </summary>
        public static string WorkOrderPrintSet_ManagePageTitle {
            get {
                return ResourceManager.GetString("WorkOrderPrintSet_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单标签设置 的本地化字符串。
        /// </summary>
        public static string WorkOrderPrintSet_ModifyTitle {
            get {
                return ResourceManager.GetString("WorkOrderPrintSet_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单标签设置（{0}）保存成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderPrintSet_Save_Success {
            get {
                return ResourceManager.GetString("WorkOrderPrintSet_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单标签设置（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderPrintSet_SaveModify_Success {
            get {
                return ResourceManager.GetString("WorkOrderPrintSet_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除工单规则（{0}）？ 的本地化字符串。
        /// </summary>
        public static string WorkOrderRule_ConfirmDelete {
            get {
                return ResourceManager.GetString("WorkOrderRule_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除工单规则（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderRule_Delete_Success {
            get {
                return ResourceManager.GetString("WorkOrderRule_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单规则信息 的本地化字符串。
        /// </summary>
        public static string WorkOrderRule_DetailTitle {
            get {
                return ResourceManager.GetString("WorkOrderRule_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单规则设置 的本地化字符串。
        /// </summary>
        public static string WorkOrderRule_ManagePageTitle {
            get {
                return ResourceManager.GetString("WorkOrderRule_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单规则 的本地化字符串。
        /// </summary>
        public static string WorkOrderRule_ModifyTitle {
            get {
                return ResourceManager.GetString("WorkOrderRule_ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单规则（{0}）保存成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderRule_Save_Success {
            get {
                return ResourceManager.GetString("WorkOrderRule_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工单规则（{0}）成功。 的本地化字符串。
        /// </summary>
        public static string WorkOrderRule_SaveModify_Success {
            get {
                return ResourceManager.GetString("WorkOrderRule_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品号 的本地化字符串。
        /// </summary>
        public static string WorkOrderRuleQueryViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("WorkOrderRuleQueryViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string WorkOrderRuleQueryViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderRuleQueryViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校准周期（分钟） 的本地化字符串。
        /// </summary>
        public static string WorkOrderRuleViewModel_CalibrationCycle {
            get {
                return ResourceManager.GetString("WorkOrderRuleViewModel_CalibrationCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校准板类型 的本地化字符串。
        /// </summary>
        public static string WorkOrderRuleViewModel_CalibrationType {
            get {
                return ResourceManager.GetString("WorkOrderRuleViewModel_CalibrationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固化周期（分钟） 的本地化字符串。
        /// </summary>
        public static string WorkOrderRuleViewModel_FixCycle {
            get {
                return ResourceManager.GetString("WorkOrderRuleViewModel_FixCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用？ 的本地化字符串。
        /// </summary>
        public static string WorkOrderRuleViewModel_IsUsed {
            get {
                return ResourceManager.GetString("WorkOrderRuleViewModel_IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品号 的本地化字符串。
        /// </summary>
        public static string WorkOrderRuleViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("WorkOrderRuleViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功率上限 的本地化字符串。
        /// </summary>
        public static string WorkOrderRuleViewModel_MaxPower {
            get {
                return ResourceManager.GetString("WorkOrderRuleViewModel_MaxPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功率下限 的本地化字符串。
        /// </summary>
        public static string WorkOrderRuleViewModel_MinPower {
            get {
                return ResourceManager.GetString("WorkOrderRuleViewModel_MinPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string WorkOrderRuleViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderRuleViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功率精度 的本地化字符串。
        /// </summary>
        public static string WorkOrderRuleViewModel_PowerDegree {
            get {
                return ResourceManager.GetString("WorkOrderRuleViewModel_PowerDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则代码 的本地化字符串。
        /// </summary>
        public static string WorkOrderRuleViewModel_RuleCode {
            get {
                return ResourceManager.GetString("WorkOrderRuleViewModel_RuleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则名称 的本地化字符串。
        /// </summary>
        public static string WorkOrderRuleViewModel_RuleName {
            get {
                return ResourceManager.GetString("WorkOrderRuleViewModel_RuleName", resourceCulture);
            }
        }
    }
}
