//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenter.MES.Model.ERP.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceCenter.MES.Model.ERP.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 入库申请 的本地化字符串。
        /// </summary>
        public static string EnumBillState_Apply {
            get {
                return ResourceManager.GetString("EnumBillState_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string EnumBillState_Create {
            get {
                return ResourceManager.GetString("EnumBillState_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库 的本地化字符串。
        /// </summary>
        public static string EnumBillState_Receive {
            get {
                return ResourceManager.GetString("EnumBillState_Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string EnumMixType_False {
            get {
                return ResourceManager.GetString("EnumMixType_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string EnumMixType_True {
            get {
                return ResourceManager.GetString("EnumMixType_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string EnumScrapType_False {
            get {
                return ResourceManager.GetString("EnumScrapType_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string EnumScrapType_True {
            get {
                return ResourceManager.GetString("EnumScrapType_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产成品入库 的本地化字符串。
        /// </summary>
        public static string EnumStockInType_Finish {
            get {
                return ResourceManager.GetString("EnumStockInType_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报废品入库 的本地化字符串。
        /// </summary>
        public static string EnumStockInType_Scrap {
            get {
                return ResourceManager.GetString("EnumStockInType_Scrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在制品入库 的本地化字符串。
        /// </summary>
        public static string EnumStockInType_Wip {
            get {
                return ResourceManager.GetString("EnumStockInType_Wip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报工单已经申报，无法添加明细 的本地化字符串。
        /// </summary>
        public static string ERPWOReportDetail_Error_WACode {
            get {
                return ResourceManager.GetString("ERPWOReportDetail_Error_WACode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他错误 ({0}) 的本地化字符串。
        /// </summary>
        public static string OtherError {
            get {
                return ResourceManager.GetString("OtherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报工单新增失败！({0}) 的本地化字符串。
        /// </summary>
        public static string WOReport_Error_Save {
            get {
                return ResourceManager.GetString("WOReport_Error_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报工单（{0}）已存在！ 的本地化字符串。
        /// </summary>
        public static string WOReportService_IsExists {
            get {
                return ResourceManager.GetString("WOReportService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报工单（{0}）不存在！ 的本地化字符串。
        /// </summary>
        public static string WOReportService_IsNotExists {
            get {
                return ResourceManager.GetString("WOReportService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单（{0}）不存在！ 的本地化字符串。
        /// </summary>
        public static string WOReportService_WorkOrderIsNotExists {
            get {
                return ResourceManager.GetString("WOReportService_WorkOrderIsNotExists", resourceCulture);
            }
        }
    }
}
