//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenter.MES.Model.ZPVM.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceCenter.MES.Model.ZPVM.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 目标 的本地化字符串。
        /// </summary>
        internal static string EnumDecayType_Aim {
            get {
                return ResourceManager.GetString("EnumDecayType_Aim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 比例 的本地化字符串。
        /// </summary>
        internal static string EnumDecayType_Rate {
            get {
                return ResourceManager.GetString("EnumDecayType_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IPM 的本地化字符串。
        /// </summary>
        internal static string EnumPowersetSubWay_IPM {
            get {
                return ResourceManager.GetString("EnumPowersetSubWay_IPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISC 的本地化字符串。
        /// </summary>
        internal static string EnumPowersetSubWay_ISC {
            get {
                return ResourceManager.GetString("EnumPowersetSubWay_ISC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string EnumPowersetSubWay_None {
            get {
                return ResourceManager.GetString("EnumPowersetSubWay_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VOC 的本地化字符串。
        /// </summary>
        internal static string EnumPowersetSubWay_VOC {
            get {
                return ResourceManager.GetString("EnumPowersetSubWay_VOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VPM 的本地化字符串。
        /// </summary>
        internal static string EnumPowersetSubWay_VPM {
            get {
                return ResourceManager.GetString("EnumPowersetSubWay_VPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试温度 的本地化字符串。
        /// </summary>
        internal static string PVMTestDataType_AmbientTemperature {
            get {
                return ResourceManager.GetString("PVMTestDataType_AmbientTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CTM 的本地化字符串。
        /// </summary>
        internal static string PVMTestDataType_CTM {
            get {
                return ResourceManager.GetString("PVMTestDataType_CTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填充因子 的本地化字符串。
        /// </summary>
        internal static string PVMTestDataType_FF {
            get {
                return ResourceManager.GetString("PVMTestDataType_FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大电流 的本地化字符串。
        /// </summary>
        internal static string PVMTestDataType_IPM {
            get {
                return ResourceManager.GetString("PVMTestDataType_IPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电流 的本地化字符串。
        /// </summary>
        internal static string PVMTestDataType_ISC {
            get {
                return ResourceManager.GetString("PVMTestDataType_ISC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功率 的本地化字符串。
        /// </summary>
        internal static string PVMTestDataType_PM {
            get {
                return ResourceManager.GetString("PVMTestDataType_PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电压 的本地化字符串。
        /// </summary>
        internal static string PVMTestDataType_VOC {
            get {
                return ResourceManager.GetString("PVMTestDataType_VOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大电压 的本地化字符串。
        /// </summary>
        internal static string PVMTestDataType_VPM {
            get {
                return ResourceManager.GetString("PVMTestDataType_VPM", resourceCulture);
            }
        }
    }
}
