//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenter.MES.Service.ZPVM.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceCenter.MES.Service.ZPVM.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 衰减数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string DecayService_IsExists {
            get {
                return ResourceManager.GetString("DecayService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 衰减数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string DecayService_IsNotExists {
            get {
                return ResourceManager.GetString("DecayService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效率档数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string EfficiencyService_IsExists {
            get {
                return ResourceManager.GetString("EfficiencyService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效率档数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string EfficiencyService_IsNotExists {
            get {
                return ResourceManager.GetString("EfficiencyService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误：{0} 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IV测试数据打印日志（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string IVTestDataPrintLogService_IsExists {
            get {
                return ResourceManager.GetString("IVTestDataPrintLogService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IV测试数据打印日志（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string IVTestDataPrintLogService_IsNotExists {
            get {
                return ResourceManager.GetString("IVTestDataPrintLogService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IV测试数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string IVTestDataService_IsExists {
            get {
                return ResourceManager.GetString("IVTestDataService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IV测试数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string IVTestDataService_IsNotExists {
            get {
                return ResourceManager.GetString("IVTestDataService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料替换规则（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string MaterialReplaceService_IsExists {
            get {
                return ResourceManager.GetString("MaterialReplaceService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料替换规则（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string MaterialReplaceService_IsNotExists {
            get {
                return ResourceManager.GetString("MaterialReplaceService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子分档数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string PowersetDetailService_IsExists {
            get {
                return ResourceManager.GetString("PowersetDetailService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子分档数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string PowersetDetailService_IsNotExists {
            get {
                return ResourceManager.GetString("PowersetDetailService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分档数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string PowersetService_IsExists {
            get {
                return ResourceManager.GetString("PowersetService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分档数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string PowersetService_IsNotExists {
            get {
                return ResourceManager.GetString("PowersetService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品控制参数设置数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string ProductControlObjectService_IsExists {
            get {
                return ResourceManager.GetString("ProductControlObjectService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品控制参数设置数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string ProductControlObjectService_IsNotExists {
            get {
                return ResourceManager.GetString("ProductControlObjectService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则-控制参数对象设置数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string RuleControlObjectService_IsExists {
            get {
                return ResourceManager.GetString("RuleControlObjectService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则-控制参数对象设置数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string RuleControlObjectService_IsNotExists {
            get {
                return ResourceManager.GetString("RuleControlObjectService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则-衰减设置数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string RuleDecayService_IsExists {
            get {
                return ResourceManager.GetString("RuleDecayService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则-衰减设置数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string RuleDecayService_IsNotExists {
            get {
                return ResourceManager.GetString("RuleDecayService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则-等级设置数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string RuleGradeService_IsExists {
            get {
                return ResourceManager.GetString("RuleGradeService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则-等级设置数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string RuleGradeService_IsNotExists {
            get {
                return ResourceManager.GetString("RuleGradeService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则-标签打印设置数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string RulePrintSetService_IsExists {
            get {
                return ResourceManager.GetString("RulePrintSetService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则-标签打印设置数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string RulePrintSetService_IsNotExists {
            get {
                return ResourceManager.GetString("RulePrintSetService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string RuleService_IsExists {
            get {
                return ResourceManager.GetString("RuleService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string RuleService_IsNotExists {
            get {
                return ResourceManager.GetString("RuleService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商转换生产厂商规则（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string SupplierToManufacturerService_IsExists {
            get {
                return ResourceManager.GetString("SupplierToManufacturerService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商转换生产厂商规则（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string SupplierToManufacturerService_IsNotExists {
            get {
                return ResourceManager.GetString("SupplierToManufacturerService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安规测试数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string VIRTestDataService_IsExists {
            get {
                return ResourceManager.GetString("VIRTestDataService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安规测试数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string VIRTestDataService_IsNotExists {
            get {
                return ResourceManager.GetString("VIRTestDataService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单控制参数设置数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string WorkOrderControlObjectService_IsExists {
            get {
                return ResourceManager.GetString("WorkOrderControlObjectService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单控制参数设置数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string WorkOrderControlObjectService_IsNotExists {
            get {
                return ResourceManager.GetString("WorkOrderControlObjectService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单衰减设置数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string WorkOrderDecayService_IsExists {
            get {
                return ResourceManager.GetString("WorkOrderDecayService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单衰减设置数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string WorkOrderDecayService_IsNotExists {
            get {
                return ResourceManager.GetString("WorkOrderDecayService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单等级设置数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string WorkOrderGradeService_IsExists {
            get {
                return ResourceManager.GetString("WorkOrderGradeService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单等级设置数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string WorkOrderGradeService_IsNotExists {
            get {
                return ResourceManager.GetString("WorkOrderGradeService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单子分档设置数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string WorkOrderPowersetDetailService_IsExists {
            get {
                return ResourceManager.GetString("WorkOrderPowersetDetailService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单子分档设置数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string WorkOrderPowersetDetailService_IsNotExists {
            get {
                return ResourceManager.GetString("WorkOrderPowersetDetailService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单分档设置数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string WorkOrderPowersetService_IsExists {
            get {
                return ResourceManager.GetString("WorkOrderPowersetService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单分档设置数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string WorkOrderPowersetService_IsNotExists {
            get {
                return ResourceManager.GetString("WorkOrderPowersetService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单标签打印设置数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string WorkOrderPrintSetService_IsExists {
            get {
                return ResourceManager.GetString("WorkOrderPrintSetService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单标签打印设置数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string WorkOrderPrintSetService_IsNotExists {
            get {
                return ResourceManager.GetString("WorkOrderPrintSetService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单规则数据（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string WorkOrderRuleService_IsExists {
            get {
                return ResourceManager.GetString("WorkOrderRuleService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单规则数据（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string WorkOrderRuleService_IsNotExists {
            get {
                return ResourceManager.GetString("WorkOrderRuleService_IsNotExists", resourceCulture);
            }
        }
    }
}
