//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenter.Client.Mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceCenter.Client.Mvc.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的旧密码错误。 的本地化字符串。
        /// </summary>
        public static string AccountController_OldPasswordError {
            get {
                return ResourceManager.GetString("AccountController_OldPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系方式 的本地化字符串。
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string CreateTime {
            get {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据 的本地化字符串。
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 明细 的本地化字符串。
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑人 的本地化字符串。
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑时间 的本地化字符串。
        /// </summary>
        public static string EditTime {
            get {
                return ResourceManager.GetString("EditTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理你的请求时出错 的本地化字符串。
        /// </summary>
        public static string ErrorPage_Text {
            get {
                return ResourceManager.GetString("ErrorPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string ErrorPage_Title {
            get {
                return ResourceManager.GetString("ErrorPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出到EXCEL 的本地化字符串。
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段 的本地化字符串。
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你好  的本地化字符串。
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string ItemNo {
            get {
                return ResourceManager.GetString("ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理 的本地化字符串。
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        public static string ModifyPassword {
            get {
                return ResourceManager.GetString("ModifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一步 的本地化字符串。
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性值 的本地化字符串。
        /// </summary>
        public static string PropertyValue {
            get {
                return ResourceManager.GetString("PropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MES 的本地化字符串。
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误代码 的本地化字符串。
        /// </summary>
        public static string Unauthorized_Code {
            get {
                return ResourceManager.GetString("Unauthorized_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细信息 的本地化字符串。
        /// </summary>
        public static string Unauthorized_Detail {
            get {
                return ResourceManager.GetString("Unauthorized_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误消息 的本地化字符串。
        /// </summary>
        public static string Unauthorized_Message {
            get {
                return ResourceManager.GetString("Unauthorized_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户访问被拒绝 的本地化字符串。
        /// </summary>
        public static string Unauthorized_PageTitle {
            get {
                return ResourceManager.GetString("Unauthorized_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 必须为图片文件（jpg|gif|jpeg|bmp|png） 的本地化字符串。
        /// </summary>
        public static string ValidateImageFileFormat {
            get {
                return ResourceManager.GetString("ValidateImageFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 需要是整数。 的本地化字符串。
        /// </summary>
        public static string ValidateInt {
            get {
                return ResourceManager.GetString("ValidateInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 不能超过 {1} 个字符。 的本地化字符串。
        /// </summary>
        public static string ValidateMaxStringLength {
            get {
                return ResourceManager.GetString("ValidateMaxStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 需要是 {1} - {2} 数字。 的本地化字符串。
        /// </summary>
        public static string ValidateRange {
            get {
                return ResourceManager.GetString("ValidateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 包含非法字符。 的本地化字符串。
        /// </summary>
        public static string ValidateString {
            get {
                return ResourceManager.GetString("ValidateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 必须至少包含 {2} 个字符，不能超过 {1} 个字符。 的本地化字符串。
        /// </summary>
        public static string ValidateStringLength {
            get {
                return ResourceManager.GetString("ValidateStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 格式必须为 HH:mm 的本地化字符串。
        /// </summary>
        public static string ValidateTimeHHMM {
            get {
                return ResourceManager.GetString("ValidateTimeHHMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
