//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenter.Client.Mvc.Resources.RPT {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceCenter.Client.Mvc.Resources.RPT.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 在制品分布报表 的本地化字符串。
        /// </summary>
        public static string WIPDisplayQuery_ManagePageTitle {
            get {
                return ResourceManager.GetString("WIPDisplayQuery_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车间名称 的本地化字符串。
        /// </summary>
        public static string WIPDisplayQueryViewModel_LocationName {
            get {
                return ResourceManager.GetString("WIPDisplayQueryViewModel_LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string WIPDisplayQueryViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("WIPDisplayQueryViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线时长（分钟） 的本地化字符串。
        /// </summary>
        public static string WIPDisplayQueryViewModel_OnlineTime {
            get {
                return ResourceManager.GetString("WIPDisplayQueryViewModel_OnlineTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string WIPDisplayQueryViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("WIPDisplayQueryViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序MOVE量报表 的本地化字符串。
        /// </summary>
        public static string WIPMoveQuery_ManagePageTitle {
            get {
                return ResourceManager.GetString("WIPMoveQuery_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束日期 的本地化字符串。
        /// </summary>
        public static string WIPMoveQueryViewModel_EndDate {
            get {
                return ResourceManager.GetString("WIPMoveQueryViewModel_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车间名称 的本地化字符串。
        /// </summary>
        public static string WIPMoveQueryViewModel_LocationName {
            get {
                return ResourceManager.GetString("WIPMoveQueryViewModel_LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string WIPMoveQueryViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("WIPMoveQueryViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string WIPMoveQueryViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("WIPMoveQueryViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 班别 的本地化字符串。
        /// </summary>
        public static string WIPMoveQueryViewModel_ShiftName {
            get {
                return ResourceManager.GetString("WIPMoveQueryViewModel_ShiftName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始日期 的本地化字符串。
        /// </summary>
        public static string WIPMoveQueryViewModel_StartDate {
            get {
                return ResourceManager.GetString("WIPMoveQueryViewModel_StartDate", resourceCulture);
            }
        }
    }
}
