//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceTest.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.jinchensolar.com/", ConfigurationName="Service.TradLevelSoap")]
    public interface TradLevelSoap {
        
        // CODEGEN: 命名空间 http://www.jinchensolar.com/ 的元素名称 m_tradId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jinchensolar.com/SetTradLevel", ReplyAction="*")]
        global::WebServiceTest.Service.SetTradLevelResponse SetTradLevel(global::WebServiceTest.Service.SetTradLevelRequest request);
        
        // CODEGEN: 命名空间 http://www.jinchensolar.com/ 的元素名称 m_tradId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jinchensolar.com/SearhModulePosition", ReplyAction="*")]
        global::WebServiceTest.Service.SearhModulePositionResponse SearhModulePosition(global::WebServiceTest.Service.SearhModulePositionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jinchensolar.com/SetLineState", ReplyAction="*")]
        bool SetLineState(int m_workShopId, int m_flowId, int m_flowSubId, int m_State);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetTradLevelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetTradLevel", Namespace="http://www.jinchensolar.com/", Order=0)]
        public global::WebServiceTest.Service.SetTradLevelRequestBody Body;
        
        public SetTradLevelRequest() {
        }
        
        public SetTradLevelRequest(global::WebServiceTest.Service.SetTradLevelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.jinchensolar.com/")]
    public partial class SetTradLevelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int m_workShopId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int m_flowId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string m_tradId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int m_Level;
        
        public SetTradLevelRequestBody() {
        }
        
        public SetTradLevelRequestBody(int m_workShopId, int m_flowId, string m_tradId, int m_Level) {
            this.m_workShopId = m_workShopId;
            this.m_flowId = m_flowId;
            this.m_tradId = m_tradId;
            this.m_Level = m_Level;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetTradLevelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetTradLevelResponse", Namespace="http://www.jinchensolar.com/", Order=0)]
        public global::WebServiceTest.Service.SetTradLevelResponseBody Body;
        
        public SetTradLevelResponse() {
        }
        
        public SetTradLevelResponse(global::WebServiceTest.Service.SetTradLevelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.jinchensolar.com/")]
    public partial class SetTradLevelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetTradLevelResult;
        
        public SetTradLevelResponseBody() {
        }
        
        public SetTradLevelResponseBody(bool SetTradLevelResult) {
            this.SetTradLevelResult = SetTradLevelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearhModulePositionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearhModulePosition", Namespace="http://www.jinchensolar.com/", Order=0)]
        public global::WebServiceTest.Service.SearhModulePositionRequestBody Body;
        
        public SearhModulePositionRequest() {
        }
        
        public SearhModulePositionRequest(global::WebServiceTest.Service.SearhModulePositionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.jinchensolar.com/")]
    public partial class SearhModulePositionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string m_tradId;
        
        public SearhModulePositionRequestBody() {
        }
        
        public SearhModulePositionRequestBody(string m_tradId) {
            this.m_tradId = m_tradId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearhModulePositionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearhModulePositionResponse", Namespace="http://www.jinchensolar.com/", Order=0)]
        public global::WebServiceTest.Service.SearhModulePositionResponseBody Body;
        
        public SearhModulePositionResponse() {
        }
        
        public SearhModulePositionResponse(global::WebServiceTest.Service.SearhModulePositionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.jinchensolar.com/")]
    public partial class SearhModulePositionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SearhModulePositionResult;
        
        public SearhModulePositionResponseBody() {
        }
        
        public SearhModulePositionResponseBody(string SearhModulePositionResult) {
            this.SearhModulePositionResult = SearhModulePositionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TradLevelSoapChannel : global::WebServiceTest.Service.TradLevelSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TradLevelSoapClient : System.ServiceModel.ClientBase<global::WebServiceTest.Service.TradLevelSoap>, global::WebServiceTest.Service.TradLevelSoap {
        
        public TradLevelSoapClient() {
        }
        
        public TradLevelSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TradLevelSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TradLevelSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TradLevelSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::WebServiceTest.Service.SetTradLevelResponse global::WebServiceTest.Service.TradLevelSoap.SetTradLevel(global::WebServiceTest.Service.SetTradLevelRequest request) {
            return base.Channel.SetTradLevel(request);
        }
        
        public bool SetTradLevel(int m_workShopId, int m_flowId, string m_tradId, int m_Level) {
            global::WebServiceTest.Service.SetTradLevelRequest inValue = new global::WebServiceTest.Service.SetTradLevelRequest();
            inValue.Body = new global::WebServiceTest.Service.SetTradLevelRequestBody();
            inValue.Body.m_workShopId = m_workShopId;
            inValue.Body.m_flowId = m_flowId;
            inValue.Body.m_tradId = m_tradId;
            inValue.Body.m_Level = m_Level;
            global::WebServiceTest.Service.SetTradLevelResponse retVal = ((global::WebServiceTest.Service.TradLevelSoap)(this)).SetTradLevel(inValue);
            return retVal.Body.SetTradLevelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::WebServiceTest.Service.SearhModulePositionResponse global::WebServiceTest.Service.TradLevelSoap.SearhModulePosition(global::WebServiceTest.Service.SearhModulePositionRequest request) {
            return base.Channel.SearhModulePosition(request);
        }
        
        public string SearhModulePosition(string m_tradId) {
            global::WebServiceTest.Service.SearhModulePositionRequest inValue = new global::WebServiceTest.Service.SearhModulePositionRequest();
            inValue.Body = new global::WebServiceTest.Service.SearhModulePositionRequestBody();
            inValue.Body.m_tradId = m_tradId;
            global::WebServiceTest.Service.SearhModulePositionResponse retVal = ((global::WebServiceTest.Service.TradLevelSoap)(this)).SearhModulePosition(inValue);
            return retVal.Body.SearhModulePositionResult;
        }
        
        public bool SetLineState(int m_workShopId, int m_flowId, int m_flowSubId, int m_State) {
            return base.Channel.SetLineState(m_workShopId, m_flowId, m_flowSubId, m_State);
        }
    }
}
