//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenter.MES.Service.FMM.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceCenter.MES.Service.FMM.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 线别【{0}】BIN（{1}）已设置为异常BIN 的本地化字符串。
        /// </summary>
        internal static string AbnormalBin_IsExists {
            get {
                return ResourceManager.GetString("AbnormalBin_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bin属性（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string BinRuleService_IsExists {
            get {
                return ResourceManager.GetString("BinRuleService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bin属性（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string BinRuleService_IsNotExists {
            get {
                return ResourceManager.GetString("BinRuleService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校准板线别属性（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string CalibrationPlateLineService_IsExists {
            get {
                return ResourceManager.GetString("CalibrationPlateLineService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校准板线别属性（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string CalibrationPlateLineService_IsNotExists {
            get {
                return ResourceManager.GetString("CalibrationPlateLineService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校准板属性（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string CalibrationPlateService_IsExists {
            get {
                return ResourceManager.GetString("CalibrationPlateService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校准板属性（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string CalibrationPlateService_IsNotExists {
            get {
                return ResourceManager.GetString("CalibrationPlateService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端属性（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string ClientConfigAttributeService_IsExists {
            get {
                return ResourceManager.GetString("ClientConfigAttributeService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端属性（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string ClientConfigAttributeService_IsNotExists {
            get {
                return ResourceManager.GetString("ClientConfigAttributeService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string ClientConfigService_IsExists {
            get {
                return ResourceManager.GetString("ClientConfigService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string ClientConfigService_IsNotExists {
            get {
                return ResourceManager.GetString("ClientConfigService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备可切换状态（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string EquipmentChangeStateService_IsExists {
            get {
                return ResourceManager.GetString("EquipmentChangeStateService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备可切换状态（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string EquipmentChangeStateService_IsNotExists {
            get {
                return ResourceManager.GetString("EquipmentChangeStateService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备异常耗时（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string EquipmentConsumingService_IsNotExists {
            get {
                return ResourceManager.GetString("EquipmentConsumingService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备控制参数（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string EquipmentControlObjectService_IsExists {
            get {
                return ResourceManager.GetString("EquipmentControlObjectService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备控制参数（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string EquipmentControlObjectService_IsNotExists {
            get {
                return ResourceManager.GetString("EquipmentControlObjectService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备组（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string EquipmentGroupService_IsExists {
            get {
                return ResourceManager.GetString("EquipmentGroupService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备组（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string EquipmentGroupService_IsNotExists {
            get {
                return ResourceManager.GetString("EquipmentGroupService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备布局明细（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string EquipmentLayoutDetailService_IsExists {
            get {
                return ResourceManager.GetString("EquipmentLayoutDetailService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备布局明细（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string EquipmentLayoutDetailService_IsNotExists {
            get {
                return ResourceManager.GetString("EquipmentLayoutDetailService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备布局（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string EquipmentLayoutService_IsExists {
            get {
                return ResourceManager.GetString("EquipmentLayoutService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备布局（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string EquipmentLayoutService_IsNotExists {
            get {
                return ResourceManager.GetString("EquipmentLayoutService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string EquipmentService_IsExists {
            get {
                return ResourceManager.GetString("EquipmentService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string EquipmentService_IsNotExists {
            get {
                return ResourceManager.GetString("EquipmentService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备状态（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string EquipmentStateService_IsExists {
            get {
                return ResourceManager.GetString("EquipmentStateService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备状态（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string EquipmentStateService_IsNotExists {
            get {
                return ResourceManager.GetString("EquipmentStateService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string LineStoreService_IsExists {
            get {
                return ResourceManager.GetString("LineStoreService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string LineStoreService_IsNotExists {
            get {
                return ResourceManager.GetString("LineStoreService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string LocationService_IsExists {
            get {
                return ResourceManager.GetString("LocationService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string LocationService_IsNotExists {
            get {
                return ResourceManager.GetString("LocationService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产厂商（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string ManufacturerService_IsExists {
            get {
                return ResourceManager.GetString("ManufacturerService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产厂商（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string ManufacturerService_IsNotExists {
            get {
                return ResourceManager.GetString("ManufacturerService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料属性（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string MaterialAttributeService_IsExists {
            get {
                return ResourceManager.GetString("MaterialAttributeService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料属性（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string MaterialAttributeService_IsNotExists {
            get {
                return ResourceManager.GetString("MaterialAttributeService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料BOM（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string MaterialBOMService_IsExists {
            get {
                return ResourceManager.GetString("MaterialBOMService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料BOM（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string MaterialBOMService_IsNotExists {
            get {
                return ResourceManager.GetString("MaterialBOMService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品编码（{0}）成柜规则已存在。 的本地化字符串。
        /// </summary>
        internal static string MaterialChestParameterService_IsExists {
            get {
                return ResourceManager.GetString("MaterialChestParameterService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品编码（{0}）成柜规则不存在。 的本地化字符串。
        /// </summary>
        internal static string MaterialChestParameterService_IsNotExists {
            get {
                return ResourceManager.GetString("MaterialChestParameterService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品标签（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string MaterialPrintSetService_IsExists {
            get {
                return ResourceManager.GetString("MaterialPrintSetService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品标签（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string MaterialPrintSetService_IsNotExists {
            get {
                return ResourceManager.GetString("MaterialPrintSetService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品工艺流程（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string MaterialRouteService_IsExists {
            get {
                return ResourceManager.GetString("MaterialRouteService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品工艺流程（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string MaterialRouteService_IsNotExists {
            get {
                return ResourceManager.GetString("MaterialRouteService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string MaterialService_IsExists {
            get {
                return ResourceManager.GetString("MaterialService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string MaterialService_IsNotExists {
            get {
                return ResourceManager.GetString("MaterialService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string MaterialTypeRouteService_IsExists {
            get {
                return ResourceManager.GetString("MaterialTypeRouteService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string MaterialTypeRouteService_IsNotExists {
            get {
                return ResourceManager.GetString("MaterialTypeRouteService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料类型（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string MaterialTypeService_IsExists {
            get {
                return ResourceManager.GetString("MaterialTypeService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料类型（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string MaterialTypeService_IsNotExists {
            get {
                return ResourceManager.GetString("MaterialTypeService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他错误（{0}）。 的本地化字符串。
        /// </summary>
        internal static string OtherError {
            get {
                return ResourceManager.GetString("OtherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string ParameterDerivationService_IsExists {
            get {
                return ResourceManager.GetString("ParameterDerivationService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string ParameterDerivationService_IsNotExists {
            get {
                return ResourceManager.GetString("ParameterDerivationService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string ParameterService_IsExists {
            get {
                return ResourceManager.GetString("ParameterService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string ParameterService_IsNotExists {
            get {
                return ResourceManager.GetString("ParameterService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印标签（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string PrintLabelService_IsExists {
            get {
                return ResourceManager.GetString("PrintLabelService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印标签（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string PrintLabelService_IsNotExists {
            get {
                return ResourceManager.GetString("PrintLabelService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产线（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string ProductionLineService_IsExists {
            get {
                return ResourceManager.GetString("ProductionLineService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产线（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string ProductionLineService_IsNotExists {
            get {
                return ResourceManager.GetString("ProductionLineService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string ReasonCodeCategoryDetailService_IsExists {
            get {
                return ResourceManager.GetString("ReasonCodeCategoryDetailService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string ReasonCodeCategoryDetailService_IsNotExists {
            get {
                return ResourceManager.GetString("ReasonCodeCategoryDetailService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码组（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string ReasonCodeCategoryService_IsExists {
            get {
                return ResourceManager.GetString("ReasonCodeCategoryService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码组（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string ReasonCodeCategoryService_IsNotExists {
            get {
                return ResourceManager.GetString("ReasonCodeCategoryService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string ReasonCodeService_IsExists {
            get {
                return ResourceManager.GetString("ReasonCodeService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string ReasonCodeService_IsNotExists {
            get {
                return ResourceManager.GetString("ReasonCodeService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string RouteEnterpriseDetailService_IsExists {
            get {
                return ResourceManager.GetString("RouteEnterpriseDetailService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string RouteEnterpriseDetailService_IsNotExists {
            get {
                return ResourceManager.GetString("RouteEnterpriseDetailService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程组（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string RouteEnterpriseService_IsExists {
            get {
                return ResourceManager.GetString("RouteEnterpriseService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程组（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string RouteEnterpriseService_IsNotExists {
            get {
                return ResourceManager.GetString("RouteEnterpriseService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序属性（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string RouteOperationAttributeService_IsExists {
            get {
                return ResourceManager.GetString("RouteOperationAttributeService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序属性（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string RouteOperationAttributeService_IsNotExists {
            get {
                return ResourceManager.GetString("RouteOperationAttributeService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序设备（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string RouteOperationEquipmentService_IsExists {
            get {
                return ResourceManager.GetString("RouteOperationEquipmentService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序设备（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string RouteOperationEquipmentService_IsNotExists {
            get {
                return ResourceManager.GetString("RouteOperationEquipmentService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序参数（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string RouteOperationParameterService_IsExists {
            get {
                return ResourceManager.GetString("RouteOperationParameterService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序参数（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string RouteOperationParameterService_IsNotExists {
            get {
                return ResourceManager.GetString("RouteOperationParameterService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string RouteOperationService_IsExists {
            get {
                return ResourceManager.GetString("RouteOperationService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string RouteOperationService_IsNotExists {
            get {
                return ResourceManager.GetString("RouteOperationService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string RouteService_IsExists {
            get {
                return ResourceManager.GetString("RouteService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string RouteService_IsNotExists {
            get {
                return ResourceManager.GetString("RouteService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程工步属性（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string RouteStepAttributeService_IsExists {
            get {
                return ResourceManager.GetString("RouteStepAttributeService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程工步属性（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string RouteStepAttributeService_IsNotExists {
            get {
                return ResourceManager.GetString("RouteStepAttributeService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程工步参数（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string RouteStepParameterService_IsExists {
            get {
                return ResourceManager.GetString("RouteStepParameterService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程工步参数（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string RouteStepParameterService_IsNotExists {
            get {
                return ResourceManager.GetString("RouteStepParameterService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程工步（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string RouteStepService_IsExists {
            get {
                return ResourceManager.GetString("RouteStepService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺流程工步（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string RouteStepService_IsNotExists {
            get {
                return ResourceManager.GetString("RouteStepService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日排班（{0:yyyy-MM-dd}）已存在。 的本地化字符串。
        /// </summary>
        internal static string ScheduleDayService_IsExists {
            get {
                return ResourceManager.GetString("ScheduleDayService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日排班（{0:yyyy-MM-dd}）不存在。 的本地化字符串。
        /// </summary>
        internal static string ScheduleDayService_IsNotExists {
            get {
                return ResourceManager.GetString("ScheduleDayService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排班计划明细（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string ScheduleDetailService_IsExists {
            get {
                return ResourceManager.GetString("ScheduleDetailService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排班计划明细（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string ScheduleDetailService_IsNotExists {
            get {
                return ResourceManager.GetString("ScheduleDetailService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月排班（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string ScheduleMonthService_IsExists {
            get {
                return ResourceManager.GetString("ScheduleMonthService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月排班（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string ScheduleMonthService_IsNotExists {
            get {
                return ResourceManager.GetString("ScheduleMonthService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排班计划（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string ScheduleService_IsExists {
            get {
                return ResourceManager.GetString("ScheduleService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排班计划（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string ScheduleService_IsNotExists {
            get {
                return ResourceManager.GetString("ScheduleService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 班别（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string ShiftService_IsExists {
            get {
                return ResourceManager.GetString("ShiftService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 班别（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string ShiftService_IsNotExists {
            get {
                return ResourceManager.GetString("ShiftService_IsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商（{0}）已存在。 的本地化字符串。
        /// </summary>
        internal static string SupplierService_IsExists {
            get {
                return ResourceManager.GetString("SupplierService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商（{0}）不存在。 的本地化字符串。
        /// </summary>
        internal static string SupplierService_IsNotExists {
            get {
                return ResourceManager.GetString("SupplierService_IsNotExists", resourceCulture);
            }
        }
    }
}
