//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenter.Client.Mvc.Resources.LSM {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceCenter.Client.Mvc.Resources.LSM.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓物料查询 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterial_ManagePageTitle {
            get {
                return ResourceManager.GetString("LineStoreMaterial_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓物料明细查询 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialDetail_ManagePageTitle {
            get {
                return ResourceManager.GetString("LineStoreMaterialDetail_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialDetailQueryViewModel_LineStoreName {
            get {
                return ResourceManager.GetString("LineStoreMaterialDetailQueryViewModel_LineStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialDetailQueryViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("LineStoreMaterialDetailQueryViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料批号 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialDetailQueryViewModel_MaterialLot {
            get {
                return ResourceManager.GetString("LineStoreMaterialDetailQueryViewModel_MaterialLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialDetailQueryViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("LineStoreMaterialDetailQueryViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前数量 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialDetailViewModel_CurrentQty {
            get {
                return ResourceManager.GetString("LineStoreMaterialDetailViewModel_CurrentQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialDetailViewModel_LineStoreName {
            get {
                return ResourceManager.GetString("LineStoreMaterialDetailViewModel_LineStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上料数量 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialDetailViewModel_LoadingQty {
            get {
                return ResourceManager.GetString("LineStoreMaterialDetailViewModel_LoadingQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialDetailViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("LineStoreMaterialDetailViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料批号 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialDetailViewModel_MaterialLot {
            get {
                return ResourceManager.GetString("LineStoreMaterialDetailViewModel_MaterialLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领料数量 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialDetailViewModel_ReceiveQty {
            get {
                return ResourceManager.GetString("LineStoreMaterialDetailViewModel_ReceiveQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退料数量 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialDetailViewModel_ReturnQty {
            get {
                return ResourceManager.GetString("LineStoreMaterialDetailViewModel_ReturnQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报废数量 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialDetailViewModel_ScrapQty {
            get {
                return ResourceManager.GetString("LineStoreMaterialDetailViewModel_ScrapQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialDetailViewModel_SupplierCode {
            get {
                return ResourceManager.GetString("LineStoreMaterialDetailViewModel_SupplierCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商批号 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialDetailViewModel_SupplierMaterialLot {
            get {
                return ResourceManager.GetString("LineStoreMaterialDetailViewModel_SupplierMaterialLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialDetailViewModel_SupplierName {
            get {
                return ResourceManager.GetString("LineStoreMaterialDetailViewModel_SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下料数量 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialDetailViewModel_UnloadingQty {
            get {
                return ResourceManager.GetString("LineStoreMaterialDetailViewModel_UnloadingQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialQueryViewModel_LineStoreName {
            get {
                return ResourceManager.GetString("LineStoreMaterialQueryViewModel_LineStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialQueryViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("LineStoreMaterialQueryViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialViewModel_LineStoreName {
            get {
                return ResourceManager.GetString("LineStoreMaterialViewModel_LineStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string LineStoreMaterialViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("LineStoreMaterialViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上料 的本地化字符串。
        /// </summary>
        public static string MaterialLoading_AddTitle {
            get {
                return ResourceManager.GetString("MaterialLoading_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上料管理 的本地化字符串。
        /// </summary>
        public static string MaterialLoading_ManagePageTitle {
            get {
                return ResourceManager.GetString("MaterialLoading_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 {0} 成功。 的本地化字符串。
        /// </summary>
        public static string MaterialLoading_Save_Success {
            get {
                return ResourceManager.GetString("MaterialLoading_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上料明细查询 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingDetail_ManagePageTitle {
            get {
                return ResourceManager.GetString("MaterialLoadingDetail_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前数量 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingDetailViewModel_CurrentQty {
            get {
                return ResourceManager.GetString("MaterialLoadingDetailViewModel_CurrentQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否显示零数据 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingDetailViewModel_IsShowZeroData {
            get {
                return ResourceManager.GetString("MaterialLoadingDetailViewModel_IsShowZeroData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目号 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingDetailViewModel_ItemNo {
            get {
                return ResourceManager.GetString("MaterialLoadingDetailViewModel_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingDetailViewModel_LineStoreName {
            get {
                return ResourceManager.GetString("MaterialLoadingDetailViewModel_LineStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上料号 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingDetailViewModel_LoadingNo {
            get {
                return ResourceManager.GetString("MaterialLoadingDetailViewModel_LoadingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上料数量 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingDetailViewModel_LoadingQty {
            get {
                return ResourceManager.GetString("MaterialLoadingDetailViewModel_LoadingQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingDetailViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("MaterialLoadingDetailViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料批号 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingDetailViewModel_MaterialLot {
            get {
                return ResourceManager.GetString("MaterialLoadingDetailViewModel_MaterialLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下料数量 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingDetailViewModel_UnloadingQty {
            get {
                return ResourceManager.GetString("MaterialLoadingDetailViewModel_UnloadingQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上料时间（止） 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingQueryViewModel_EndLoadingTime {
            get {
                return ResourceManager.GetString("MaterialLoadingQueryViewModel_EndLoadingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingQueryViewModel_EquipmentCode {
            get {
                return ResourceManager.GetString("MaterialLoadingQueryViewModel_EquipmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上料号 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingQueryViewModel_LoadingNo {
            get {
                return ResourceManager.GetString("MaterialLoadingQueryViewModel_LoadingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产线 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingQueryViewModel_ProductionLineCode {
            get {
                return ResourceManager.GetString("MaterialLoadingQueryViewModel_ProductionLineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingQueryViewModel_RouteOperationName {
            get {
                return ResourceManager.GetString("MaterialLoadingQueryViewModel_RouteOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上料时间（起） 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingQueryViewModel_StartLoadingTime {
            get {
                return ResourceManager.GetString("MaterialLoadingQueryViewModel_StartLoadingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下料号 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingQueryViewModel_UnloadingNo {
            get {
                return ResourceManager.GetString("MaterialLoadingQueryViewModel_UnloadingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingViewModel_EquipmentCode {
            get {
                return ResourceManager.GetString("MaterialLoadingViewModel_EquipmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上料号 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingViewModel_LoadingNo {
            get {
                return ResourceManager.GetString("MaterialLoadingViewModel_LoadingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上料时间 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingViewModel_LoadingTime {
            get {
                return ResourceManager.GetString("MaterialLoadingViewModel_LoadingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作人 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingViewModel_Operator {
            get {
                return ResourceManager.GetString("MaterialLoadingViewModel_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("MaterialLoadingViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产线 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingViewModel_ProductionLineCode {
            get {
                return ResourceManager.GetString("MaterialLoadingViewModel_ProductionLineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序 的本地化字符串。
        /// </summary>
        public static string MaterialLoadingViewModel_RouteOperationName {
            get {
                return ResourceManager.GetString("MaterialLoadingViewModel_RouteOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领料 的本地化字符串。
        /// </summary>
        public static string MaterialReceipt_AddTitle {
            get {
                return ResourceManager.GetString("MaterialReceipt_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领料管理 的本地化字符串。
        /// </summary>
        public static string MaterialReceipt_ManagePageTitle {
            get {
                return ResourceManager.GetString("MaterialReceipt_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 {0} 成功。 的本地化字符串。
        /// </summary>
        public static string MaterialReceipt_Save_Success {
            get {
                return ResourceManager.GetString("MaterialReceipt_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领料明细查询 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptDetail_ManagePageTitle {
            get {
                return ResourceManager.GetString("MaterialReceiptDetail_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptDetailQueryViewModel_LineStoreName {
            get {
                return ResourceManager.GetString("MaterialReceiptDetailQueryViewModel_LineStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptDetailQueryViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("MaterialReceiptDetailQueryViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料批号 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptDetailQueryViewModel_MaterialLot {
            get {
                return ResourceManager.GetString("MaterialReceiptDetailQueryViewModel_MaterialLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领料号 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptDetailQueryViewModel_ReceiptNo {
            get {
                return ResourceManager.GetString("MaterialReceiptDetailQueryViewModel_ReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目号 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptDetailViewModel_ItemNo {
            get {
                return ResourceManager.GetString("MaterialReceiptDetailViewModel_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptDetailViewModel_LineStoreName {
            get {
                return ResourceManager.GetString("MaterialReceiptDetailViewModel_LineStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptDetailViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("MaterialReceiptDetailViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料批号 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptDetailViewModel_MaterialLot {
            get {
                return ResourceManager.GetString("MaterialReceiptDetailViewModel_MaterialLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptDetailViewModel_Qty {
            get {
                return ResourceManager.GetString("MaterialReceiptDetailViewModel_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领料号 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptDetailViewModel_ReceiptNo {
            get {
                return ResourceManager.GetString("MaterialReceiptDetailViewModel_ReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商代码 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptDetailViewModel_SupplierCode {
            get {
                return ResourceManager.GetString("MaterialReceiptDetailViewModel_SupplierCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商批号 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptDetailViewModel_SupplierMaterialLot {
            get {
                return ResourceManager.GetString("MaterialReceiptDetailViewModel_SupplierMaterialLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商名称 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptDetailViewModel_SupplierName {
            get {
                return ResourceManager.GetString("MaterialReceiptDetailViewModel_SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领料日期（止） 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptQueryViewModel_EndReceiptDate {
            get {
                return ResourceManager.GetString("MaterialReceiptQueryViewModel_EndReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptQueryViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("MaterialReceiptQueryViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领料号 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptQueryViewModel_ReceiptNo {
            get {
                return ResourceManager.GetString("MaterialReceiptQueryViewModel_ReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领料日期（起） 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptQueryViewModel_StartReceiptDate {
            get {
                return ResourceManager.GetString("MaterialReceiptQueryViewModel_StartReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("MaterialReceiptViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领料日期 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptViewModel_ReceiptDate {
            get {
                return ResourceManager.GetString("MaterialReceiptViewModel_ReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领料号 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptViewModel_ReceiptNo {
            get {
                return ResourceManager.GetString("MaterialReceiptViewModel_ReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string MaterialReceiptViewModel_Type {
            get {
                return ResourceManager.GetString("MaterialReceiptViewModel_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退料 的本地化字符串。
        /// </summary>
        public static string MaterialReturn_AddTitle {
            get {
                return ResourceManager.GetString("MaterialReturn_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退料管理 的本地化字符串。
        /// </summary>
        public static string MaterialReturn_ManagePageTitle {
            get {
                return ResourceManager.GetString("MaterialReturn_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 {0} 成功。 的本地化字符串。
        /// </summary>
        public static string MaterialReturn_Save_Success {
            get {
                return ResourceManager.GetString("MaterialReturn_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退料明细查询 的本地化字符串。
        /// </summary>
        public static string MaterialReturnDetail_ManagePageTitle {
            get {
                return ResourceManager.GetString("MaterialReturnDetail_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓 的本地化字符串。
        /// </summary>
        public static string MaterialReturnDetailQueryViewModel_LineStoreName {
            get {
                return ResourceManager.GetString("MaterialReturnDetailQueryViewModel_LineStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string MaterialReturnDetailQueryViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("MaterialReturnDetailQueryViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料批号 的本地化字符串。
        /// </summary>
        public static string MaterialReturnDetailQueryViewModel_MaterialLot {
            get {
                return ResourceManager.GetString("MaterialReturnDetailQueryViewModel_MaterialLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退料号 的本地化字符串。
        /// </summary>
        public static string MaterialReturnDetailQueryViewModel_ReturnNo {
            get {
                return ResourceManager.GetString("MaterialReturnDetailQueryViewModel_ReturnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目号 的本地化字符串。
        /// </summary>
        public static string MaterialReturnDetailViewModel_ItemNo {
            get {
                return ResourceManager.GetString("MaterialReturnDetailViewModel_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓 的本地化字符串。
        /// </summary>
        public static string MaterialReturnDetailViewModel_LineStoreName {
            get {
                return ResourceManager.GetString("MaterialReturnDetailViewModel_LineStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string MaterialReturnDetailViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("MaterialReturnDetailViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料批号 的本地化字符串。
        /// </summary>
        public static string MaterialReturnDetailViewModel_MaterialLot {
            get {
                return ResourceManager.GetString("MaterialReturnDetailViewModel_MaterialLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string MaterialReturnDetailViewModel_Qty {
            get {
                return ResourceManager.GetString("MaterialReturnDetailViewModel_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退料号 的本地化字符串。
        /// </summary>
        public static string MaterialReturnDetailViewModel_ReturnNo {
            get {
                return ResourceManager.GetString("MaterialReturnDetailViewModel_ReturnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退料日期（止） 的本地化字符串。
        /// </summary>
        public static string MaterialReturnQueryViewModel_EndReturnDate {
            get {
                return ResourceManager.GetString("MaterialReturnQueryViewModel_EndReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string MaterialReturnQueryViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("MaterialReturnQueryViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退料号 的本地化字符串。
        /// </summary>
        public static string MaterialReturnQueryViewModel_ReturnNo {
            get {
                return ResourceManager.GetString("MaterialReturnQueryViewModel_ReturnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退料日期（起） 的本地化字符串。
        /// </summary>
        public static string MaterialReturnQueryViewModel_StartReturnDate {
            get {
                return ResourceManager.GetString("MaterialReturnQueryViewModel_StartReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string MaterialReturnViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("MaterialReturnViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退料日期 的本地化字符串。
        /// </summary>
        public static string MaterialReturnViewModel_ReturnDate {
            get {
                return ResourceManager.GetString("MaterialReturnViewModel_ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退料号 的本地化字符串。
        /// </summary>
        public static string MaterialReturnViewModel_ReturnNo {
            get {
                return ResourceManager.GetString("MaterialReturnViewModel_ReturnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string MaterialReturnViewModel_Type {
            get {
                return ResourceManager.GetString("MaterialReturnViewModel_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓物料报废 的本地化字符串。
        /// </summary>
        public static string MaterialScrap_AddTitle {
            get {
                return ResourceManager.GetString("MaterialScrap_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓物料报废管理 的本地化字符串。
        /// </summary>
        public static string MaterialScrap_ManagePageTitle {
            get {
                return ResourceManager.GetString("MaterialScrap_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存线边仓物料报废 {0} 成功。 的本地化字符串。
        /// </summary>
        public static string MaterialScrap_Save_Success {
            get {
                return ResourceManager.GetString("MaterialScrap_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓物料报废明细查询 的本地化字符串。
        /// </summary>
        public static string MaterialScrapDetail_ManagePageTitle {
            get {
                return ResourceManager.GetString("MaterialScrapDetail_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓 的本地化字符串。
        /// </summary>
        public static string MaterialScrapDetailQueryViewModel_LineStoreName {
            get {
                return ResourceManager.GetString("MaterialScrapDetailQueryViewModel_LineStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string MaterialScrapDetailQueryViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("MaterialScrapDetailQueryViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料批号 的本地化字符串。
        /// </summary>
        public static string MaterialScrapDetailQueryViewModel_MaterialLot {
            get {
                return ResourceManager.GetString("MaterialScrapDetailQueryViewModel_MaterialLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报废号 的本地化字符串。
        /// </summary>
        public static string MaterialScrapDetailQueryViewModel_ScrapNo {
            get {
                return ResourceManager.GetString("MaterialScrapDetailQueryViewModel_ScrapNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目号 的本地化字符串。
        /// </summary>
        public static string MaterialScrapDetailViewModel_ItemNo {
            get {
                return ResourceManager.GetString("MaterialScrapDetailViewModel_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓 的本地化字符串。
        /// </summary>
        public static string MaterialScrapDetailViewModel_LineStoreName {
            get {
                return ResourceManager.GetString("MaterialScrapDetailViewModel_LineStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string MaterialScrapDetailViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("MaterialScrapDetailViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料批号 的本地化字符串。
        /// </summary>
        public static string MaterialScrapDetailViewModel_MaterialLot {
            get {
                return ResourceManager.GetString("MaterialScrapDetailViewModel_MaterialLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string MaterialScrapDetailViewModel_Qty {
            get {
                return ResourceManager.GetString("MaterialScrapDetailViewModel_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报废号 的本地化字符串。
        /// </summary>
        public static string MaterialScrapDetailViewModel_ScrapNo {
            get {
                return ResourceManager.GetString("MaterialScrapDetailViewModel_ScrapNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报废日期（止） 的本地化字符串。
        /// </summary>
        public static string MaterialScrapQueryViewModel_EndScrapDate {
            get {
                return ResourceManager.GetString("MaterialScrapQueryViewModel_EndScrapDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string MaterialScrapQueryViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("MaterialScrapQueryViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报废号 的本地化字符串。
        /// </summary>
        public static string MaterialScrapQueryViewModel_ScrapNo {
            get {
                return ResourceManager.GetString("MaterialScrapQueryViewModel_ScrapNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报废日期（起） 的本地化字符串。
        /// </summary>
        public static string MaterialScrapQueryViewModel_StartScrapDate {
            get {
                return ResourceManager.GetString("MaterialScrapQueryViewModel_StartScrapDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string MaterialScrapViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("MaterialScrapViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报废日期 的本地化字符串。
        /// </summary>
        public static string MaterialScrapViewModel_ScrapDate {
            get {
                return ResourceManager.GetString("MaterialScrapViewModel_ScrapDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报废号 的本地化字符串。
        /// </summary>
        public static string MaterialScrapViewModel_ScrapNo {
            get {
                return ResourceManager.GetString("MaterialScrapViewModel_ScrapNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string MaterialScrapViewModel_Type {
            get {
                return ResourceManager.GetString("MaterialScrapViewModel_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下料 的本地化字符串。
        /// </summary>
        public static string MaterialUnloading_AddTitle {
            get {
                return ResourceManager.GetString("MaterialUnloading_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下料管理 的本地化字符串。
        /// </summary>
        public static string MaterialUnloading_ManagePageTitle {
            get {
                return ResourceManager.GetString("MaterialUnloading_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 {0} 成功。 的本地化字符串。
        /// </summary>
        public static string MaterialUnloading_Save_Success {
            get {
                return ResourceManager.GetString("MaterialUnloading_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下料明细查询 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingDetail_ManagePageTitle {
            get {
                return ResourceManager.GetString("MaterialUnloadingDetail_ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目号 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingDetailViewModel_ItemNo {
            get {
                return ResourceManager.GetString("MaterialUnloadingDetailViewModel_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线边仓 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingDetailViewModel_LineStoreName {
            get {
                return ResourceManager.GetString("MaterialUnloadingDetailViewModel_LineStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上料项目号 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingDetailViewModel_LoadingItemNo {
            get {
                return ResourceManager.GetString("MaterialUnloadingDetailViewModel_LoadingItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上料号 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingDetailViewModel_LoadingNo {
            get {
                return ResourceManager.GetString("MaterialUnloadingDetailViewModel_LoadingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingDetailViewModel_MaterialCode {
            get {
                return ResourceManager.GetString("MaterialUnloadingDetailViewModel_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料批号 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingDetailViewModel_MaterialLot {
            get {
                return ResourceManager.GetString("MaterialUnloadingDetailViewModel_MaterialLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下料号 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingDetailViewModel_UnloadingNo {
            get {
                return ResourceManager.GetString("MaterialUnloadingDetailViewModel_UnloadingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下料数量 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingDetailViewModel_UnloadingQty {
            get {
                return ResourceManager.GetString("MaterialUnloadingDetailViewModel_UnloadingQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下料时间（止） 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingQueryViewModel_EndUnloadingTime {
            get {
                return ResourceManager.GetString("MaterialUnloadingQueryViewModel_EndUnloadingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingQueryViewModel_EquipmentCode {
            get {
                return ResourceManager.GetString("MaterialUnloadingQueryViewModel_EquipmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产线 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingQueryViewModel_ProductionLineCode {
            get {
                return ResourceManager.GetString("MaterialUnloadingQueryViewModel_ProductionLineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingQueryViewModel_RouteOperationName {
            get {
                return ResourceManager.GetString("MaterialUnloadingQueryViewModel_RouteOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下料时间（起） 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingQueryViewModel_StartUnloadingTime {
            get {
                return ResourceManager.GetString("MaterialUnloadingQueryViewModel_StartUnloadingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingViewModel_EquipmentCode {
            get {
                return ResourceManager.GetString("MaterialUnloadingViewModel_EquipmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作人 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingViewModel_Operator {
            get {
                return ResourceManager.GetString("MaterialUnloadingViewModel_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingViewModel_OrderNumber {
            get {
                return ResourceManager.GetString("MaterialUnloadingViewModel_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产线 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingViewModel_ProductionLineCode {
            get {
                return ResourceManager.GetString("MaterialUnloadingViewModel_ProductionLineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingViewModel_RouteOperationName {
            get {
                return ResourceManager.GetString("MaterialUnloadingViewModel_RouteOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下料号 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingViewModel_UnloadingNo {
            get {
                return ResourceManager.GetString("MaterialUnloadingViewModel_UnloadingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下料时间 的本地化字符串。
        /// </summary>
        public static string MaterialUnloadingViewModel_UnloadingTime {
            get {
                return ResourceManager.GetString("MaterialUnloadingViewModel_UnloadingTime", resourceCulture);
            }
        }
    }
}
