//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenter.Client.Mvc.Resources.RBAC {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceCenter.Client.Mvc.Resources.RBAC.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string Resource_Add {
            get {
                return ResourceManager.GetString("Resource_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增资源 的本地化字符串。
        /// </summary>
        public static string Resource_AddResourceTitle {
            get {
                return ResourceManager.GetString("Resource_AddResourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除资源 {0}-{1} ? 的本地化字符串。
        /// </summary>
        public static string Resource_ConfirmDeleteResource {
            get {
                return ResourceManager.GetString("Resource_ConfirmDeleteResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Resource_Delete {
            get {
                return ResourceManager.GetString("Resource_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1000：参数错误。 的本地化字符串。
        /// </summary>
        public static string Resource_Delete_ParamterError {
            get {
                return ResourceManager.GetString("Resource_Delete_ParamterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除资源 {0}-{1} 成功。 的本地化字符串。
        /// </summary>
        public static string Resource_Delete_Success {
            get {
                return ResourceManager.GetString("Resource_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 明细 的本地化字符串。
        /// </summary>
        public static string Resource_Detail {
            get {
                return ResourceManager.GetString("Resource_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1001：参数错误。 的本地化字符串。
        /// </summary>
        public static string Resource_Detail_ParamterError {
            get {
                return ResourceManager.GetString("Resource_Detail_ParamterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string Resource_ItemNo {
            get {
                return ResourceManager.GetString("Resource_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string Resource_Modify {
            get {
                return ResourceManager.GetString("Resource_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1002：参数错误。 的本地化字符串。
        /// </summary>
        public static string Resource_Modify_ParamterError {
            get {
                return ResourceManager.GetString("Resource_Modify_ParamterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改资源 的本地化字符串。
        /// </summary>
        public static string Resource_ModifyResourceTitle {
            get {
                return ResourceManager.GetString("Resource_ModifyResourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string Resource_Query {
            get {
                return ResourceManager.GetString("Resource_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Resource_Reset {
            get {
                return ResourceManager.GetString("Resource_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源明细 的本地化字符串。
        /// </summary>
        public static string Resource_ResourceDetailTitle {
            get {
                return ResourceManager.GetString("Resource_ResourceDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源管理 的本地化字符串。
        /// </summary>
        public static string Resource_ResourceManagePageTitle {
            get {
                return ResourceManager.GetString("Resource_ResourceManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        public static string Resource_ResourceQueryViewModel_ResourceCode {
            get {
                return ResourceManager.GetString("Resource_ResourceQueryViewModel_ResourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Resource_ResourceQueryViewModel_ResourceName {
            get {
                return ResourceManager.GetString("Resource_ResourceQueryViewModel_ResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string Resource_ResourceQueryViewModel_ResourceType {
            get {
                return ResourceManager.GetString("Resource_ResourceQueryViewModel_ResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string Resource_ResourceViewModel_CreateTime {
            get {
                return ResourceManager.GetString("Resource_ResourceViewModel_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string Resource_ResourceViewModel_Creator {
            get {
                return ResourceManager.GetString("Resource_ResourceViewModel_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Resource_ResourceViewModel_Description {
            get {
                return ResourceManager.GetString("Resource_ResourceViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 不能超过 {1} 个字符。 的本地化字符串。
        /// </summary>
        public static string Resource_ResourceViewModel_DescriptionValidateStringLength {
            get {
                return ResourceManager.GetString("Resource_ResourceViewModel_DescriptionValidateStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑人 的本地化字符串。
        /// </summary>
        public static string Resource_ResourceViewModel_Editor {
            get {
                return ResourceManager.GetString("Resource_ResourceViewModel_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑时间 的本地化字符串。
        /// </summary>
        public static string Resource_ResourceViewModel_EditTime {
            get {
                return ResourceManager.GetString("Resource_ResourceViewModel_EditTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        public static string Resource_ResourceViewModel_ResourceCode {
            get {
                return ResourceManager.GetString("Resource_ResourceViewModel_ResourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 必须至少包含 {2} 个字符，不能超过 {1} 个字符。 的本地化字符串。
        /// </summary>
        public static string Resource_ResourceViewModel_ResourceCodeValidateStringLength {
            get {
                return ResourceManager.GetString("Resource_ResourceViewModel_ResourceCodeValidateStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据 的本地化字符串。
        /// </summary>
        public static string Resource_ResourceViewModel_ResourceData {
            get {
                return ResourceManager.GetString("Resource_ResourceViewModel_ResourceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 必须至少包含 {2} 个字符，不能超过 {1} 个字符。 的本地化字符串。
        /// </summary>
        public static string Resource_ResourceViewModel_ResourceDataValidateStringLength {
            get {
                return ResourceManager.GetString("Resource_ResourceViewModel_ResourceDataValidateStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Resource_ResourceViewModel_ResourceName {
            get {
                return ResourceManager.GetString("Resource_ResourceViewModel_ResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 必须至少包含 {2} 个字符，不能超过 {1} 个字符。 的本地化字符串。
        /// </summary>
        public static string Resource_ResourceViewModel_ResourceNameValidateStringLength {
            get {
                return ResourceManager.GetString("Resource_ResourceViewModel_ResourceNameValidateStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string Resource_ResourceViewModel_ResourceType {
            get {
                return ResourceManager.GetString("Resource_ResourceViewModel_ResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Resource_Save {
            get {
                return ResourceManager.GetString("Resource_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改资源 {0}-{1} 成功。 的本地化字符串。
        /// </summary>
        public static string Resource_SaveModify_Success {
            get {
                return ResourceManager.GetString("Resource_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存资源 {0}-{1} 成功。 的本地化字符串。
        /// </summary>
        public static string Resource_SaveResource_Success {
            get {
                return ResourceManager.GetString("Resource_SaveResource_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string Role_Add {
            get {
                return ResourceManager.GetString("Role_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增角色 的本地化字符串。
        /// </summary>
        public static string Role_AddRoleTitle {
            get {
                return ResourceManager.GetString("Role_AddRoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除角色 {0} ？ 的本地化字符串。
        /// </summary>
        public static string Role_ConfirmDeleteRole {
            get {
                return ResourceManager.GetString("Role_ConfirmDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Role_Delete {
            get {
                return ResourceManager.GetString("Role_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除角色 {0} 成功。 的本地化字符串。
        /// </summary>
        public static string Role_Delete_Success {
            get {
                return ResourceManager.GetString("Role_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 明细 的本地化字符串。
        /// </summary>
        public static string Role_Detail {
            get {
                return ResourceManager.GetString("Role_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string Role_ItemNo {
            get {
                return ResourceManager.GetString("Role_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string Role_Modify {
            get {
                return ResourceManager.GetString("Role_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改角色 的本地化字符串。
        /// </summary>
        public static string Role_ModifyRoleTitle {
            get {
                return ResourceManager.GetString("Role_ModifyRoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string Role_Query {
            get {
                return ResourceManager.GetString("Role_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Role_Reset {
            get {
                return ResourceManager.GetString("Role_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色明细 的本地化字符串。
        /// </summary>
        public static string Role_RoleDetailTitle {
            get {
                return ResourceManager.GetString("Role_RoleDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色管理 的本地化字符串。
        /// </summary>
        public static string Role_RoleManagePageTitle {
            get {
                return ResourceManager.GetString("Role_RoleManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名 的本地化字符串。
        /// </summary>
        public static string Role_RoleQueryViewModel_RoleName {
            get {
                return ResourceManager.GetString("Role_RoleQueryViewModel_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string Role_RoleViewModel_CreateTime {
            get {
                return ResourceManager.GetString("Role_RoleViewModel_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string Role_RoleViewModel_Creator {
            get {
                return ResourceManager.GetString("Role_RoleViewModel_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Role_RoleViewModel_Description {
            get {
                return ResourceManager.GetString("Role_RoleViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 不能超过 {1} 个字符。 的本地化字符串。
        /// </summary>
        public static string Role_RoleViewModel_DescriptionValidateStringLength {
            get {
                return ResourceManager.GetString("Role_RoleViewModel_DescriptionValidateStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑人 的本地化字符串。
        /// </summary>
        public static string Role_RoleViewModel_Editor {
            get {
                return ResourceManager.GetString("Role_RoleViewModel_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑时间 的本地化字符串。
        /// </summary>
        public static string Role_RoleViewModel_EditTime {
            get {
                return ResourceManager.GetString("Role_RoleViewModel_EditTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名 的本地化字符串。
        /// </summary>
        public static string Role_RoleViewModel_RoleName {
            get {
                return ResourceManager.GetString("Role_RoleViewModel_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 必须至少包含 {2} 个字符，不能超过 {1} 个字符。 的本地化字符串。
        /// </summary>
        public static string Role_RoleViewModel_RoleNameValidateStringLength {
            get {
                return ResourceManager.GetString("Role_RoleViewModel_RoleNameValidateStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Role_Save {
            get {
                return ResourceManager.GetString("Role_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改角色 {0} 成功。 的本地化字符串。
        /// </summary>
        public static string Role_SaveModify_Success {
            get {
                return ResourceManager.GetString("Role_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存角色 {0} 成功。 的本地化字符串。
        /// </summary>
        public static string Role_SaveRole_Success {
            get {
                return ResourceManager.GetString("Role_SaveRole_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string User_Add {
            get {
                return ResourceManager.GetString("User_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增用户 的本地化字符串。
        /// </summary>
        public static string User_AddUserTitle {
            get {
                return ResourceManager.GetString("User_AddUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除用户 {0} ？ 的本地化字符串。
        /// </summary>
        public static string User_ConfirmDeleteUser {
            get {
                return ResourceManager.GetString("User_ConfirmDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string User_Delete {
            get {
                return ResourceManager.GetString("User_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除用户 {0} 成功。 的本地化字符串。
        /// </summary>
        public static string User_Delete_Success {
            get {
                return ResourceManager.GetString("User_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 明细 的本地化字符串。
        /// </summary>
        public static string User_Detail {
            get {
                return ResourceManager.GetString("User_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string User_ItemNo {
            get {
                return ResourceManager.GetString("User_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string User_Modify {
            get {
                return ResourceManager.GetString("User_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改用户 的本地化字符串。
        /// </summary>
        public static string User_ModifyUserTitle {
            get {
                return ResourceManager.GetString("User_ModifyUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string User_Query {
            get {
                return ResourceManager.GetString("User_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string User_Reset {
            get {
                return ResourceManager.GetString("User_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string User_Save {
            get {
                return ResourceManager.GetString("User_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改用户 {0} 成功。 的本地化字符串。
        /// </summary>
        public static string User_SaveModify_Success {
            get {
                return ResourceManager.GetString("User_SaveModify_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增用户 {0} 成功。 的本地化字符串。
        /// </summary>
        public static string User_SaveUser_Success {
            get {
                return ResourceManager.GetString("User_SaveUser_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户明细 的本地化字符串。
        /// </summary>
        public static string User_UserDetailTitle {
            get {
                return ResourceManager.GetString("User_UserDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        public static string User_UserManagePageTitle {
            get {
                return ResourceManager.GetString("User_UserManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录名 的本地化字符串。
        /// </summary>
        public static string User_UserQueryViewModel_LoginName {
            get {
                return ResourceManager.GetString("User_UserQueryViewModel_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string User_UserQueryViewModel_UserName {
            get {
                return ResourceManager.GetString("User_UserQueryViewModel_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_CreateTime {
            get {
                return ResourceManager.GetString("User_UserViewModel_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_Creator {
            get {
                return ResourceManager.GetString("User_UserViewModel_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_Description {
            get {
                return ResourceManager.GetString("User_UserViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 不能超过 {1} 个字符。 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_DescriptionValidateStringLength {
            get {
                return ResourceManager.GetString("User_UserViewModel_DescriptionValidateStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑人 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_Editor {
            get {
                return ResourceManager.GetString("User_UserViewModel_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑时间 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_EditTime {
            get {
                return ResourceManager.GetString("User_UserViewModel_EditTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮件 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_Email {
            get {
                return ResourceManager.GetString("User_UserViewModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 格式不正确。 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_EmalValidateFormat {
            get {
                return ResourceManager.GetString("User_UserViewModel_EmalValidateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激活 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_IsActive {
            get {
                return ResourceManager.GetString("User_UserViewModel_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_IsApproved {
            get {
                return ResourceManager.GetString("User_UserViewModel_IsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_IsLocked {
            get {
                return ResourceManager.GetString("User_UserViewModel_IsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后登陆IP 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_LastLoginIP {
            get {
                return ResourceManager.GetString("User_UserViewModel_LastLoginIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后登陆时间 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_LastLoginTime {
            get {
                return ResourceManager.GetString("User_UserViewModel_LastLoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录名 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_LoginName {
            get {
                return ResourceManager.GetString("User_UserViewModel_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 必须至少包含 {2} 个字符，不能超过 {1} 个字符。 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_LoginNameValidateStringLength {
            get {
                return ResourceManager.GetString("User_UserViewModel_LoginNameValidateStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动电话 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_MobilePhone {
            get {
                return ResourceManager.GetString("User_UserViewModel_MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 格式不正确。 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_MobilePhoneValidateFormat {
            get {
                return ResourceManager.GetString("User_UserViewModel_MobilePhoneValidateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 办公电话 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_OfficePhone {
            get {
                return ResourceManager.GetString("User_UserViewModel_OfficePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 格式不正确。 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_OfficePhoneValidateFormat {
            get {
                return ResourceManager.GetString("User_UserViewModel_OfficePhoneValidateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_Password {
            get {
                return ResourceManager.GetString("User_UserViewModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 必须至少包含 {2} 个字符，不能超过 {1} 个字符。 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_PasswordValidateStringLength {
            get {
                return ResourceManager.GetString("User_UserViewModel_PasswordValidateStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_UserName {
            get {
                return ResourceManager.GetString("User_UserViewModel_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 必须至少包含 {2} 个字符，不能超过 {1} 个字符。 的本地化字符串。
        /// </summary>
        public static string User_UserViewModel_UserNameValidateStringLength {
            get {
                return ResourceManager.GetString("User_UserViewModel_UserNameValidateStringLength", resourceCulture);
            }
        }
    }
}
